@extends('layouts.app')
@section('title', 'Validasi Operasional PKPA')
@section('page_title', 'Validasi Operasional PKPA')
@section('content')
<div class="space-y-5">
    @if($errors->any())<div class="rounded-2xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm font-bold text-rose-700">{{ $errors->first() }}</div>@endif
    <section class="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-sky-100"><p class="text-xs font-black uppercase tracking-widest text-cyan-700">{{ $run->student_core_user_id }}</p><h2 class="mt-1 text-2xl font-black">{{ $run->practiceSite?->name }}</h2></section>
    <div class="grid gap-5 xl:grid-cols-2">
        <section class="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-sky-100"><h3 class="text-lg font-black">Presensi Terkirim</h3><div class="mt-4 space-y-3">@foreach($run->attendanceRecords->where('submission_status', 'submitted') as $record)<form method="POST" action="{{ route('field-supervisor.pkpa-attendance.review', $record) }}" class="rounded-xl bg-slate-50 p-3">@csrf<p class="font-bold">{{ $record->attendance_date?->format('d M Y') }} / {{ $record->check_in_time }}-{{ $record->check_out_time }}</p><textarea name="notes" class="mt-2 w-full rounded-xl border-slate-200 text-sm" placeholder="Catatan validasi"></textarea><div class="mt-2 flex flex-wrap gap-2"><button name="action" value="approved" class="rounded-lg bg-emerald-600 px-3 py-1.5 text-xs font-black text-white">Setujui</button><button name="action" value="revision_requested" class="rounded-lg border border-amber-200 px-3 py-1.5 text-xs font-black text-amber-700">Revisi</button><button name="action" value="rejected" class="rounded-lg border border-rose-200 px-3 py-1.5 text-xs font-black text-rose-700">Tolak</button></div></form>@endforeach</div></section>
        <section class="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-sky-100"><h3 class="text-lg font-black">Logbook Terkirim</h3><div class="mt-4 space-y-3">@foreach($run->logbookEntries->where('status', 'submitted') as $entry)<form method="POST" action="{{ route('field-supervisor.pkpa-logbooks.review', $entry) }}" class="rounded-xl bg-slate-50 p-3">@csrf<p class="font-bold">{{ $entry->title }}</p><p class="mt-1 text-sm text-slate-500">{{ $entry->activity_summary }}</p><textarea name="comments" class="mt-2 w-full rounded-xl border-slate-200 text-sm" placeholder="Catatan review"></textarea><div class="mt-2 flex flex-wrap gap-2"><button name="action" value="approved" class="rounded-lg bg-emerald-600 px-3 py-1.5 text-xs font-black text-white">Setujui</button><button name="action" value="revision_requested" class="rounded-lg border border-amber-200 px-3 py-1.5 text-xs font-black text-amber-700">Revisi</button><button name="action" value="rejected" class="rounded-lg border border-rose-200 px-3 py-1.5 text-xs font-black text-rose-700">Tolak</button></div></form>@endforeach</div></section>
    </div>
</div>
@endsection
