@extends('layouts.app')
@section('title', 'Validasi Operasional PKPA')
@section('page_title', 'Validasi Operasional PKPA')
@section('content')
@php $back = route('field-supervisor.pkpa-operations.show', $run); @endphp
<div class="space-y-5">
@if(session('status'))<div class="rounded-2xl bg-emerald-50 p-3 text-sm font-bold text-emerald-700">{{ session('status') }}</div>@endif
@if($errors->any())<div class="rounded-2xl bg-rose-50 p-3 text-sm font-bold text-rose-700">{{ $errors->first() }}</div>@endif
@if($selectedAttendance)
<a href="{{ $back }}" class="inline-flex rounded-xl border border-slate-200 bg-white px-4 py-2 text-sm font-bold">Kembali ke Daftar</a><section class="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><h2 class="text-2xl font-black">Presensi {{ $selectedAttendance->attendance_date?->format('d M Y') }}</h2><p class="mt-2">{{ $selectedAttendance->attendance_type }} · {{ $selectedAttendance->check_in_time }} - {{ $selectedAttendance->check_out_time }}</p><p class="mt-3 rounded-xl bg-slate-50 p-4 text-sm">{{ $selectedAttendance->student_notes ?: 'Tanpa catatan.' }}</p>@if($selectedAttendance->submission_status === 'submitted')<form method="POST" action="{{ route('field-supervisor.pkpa-attendance.review', $selectedAttendance) }}" class="mt-5">@csrf<textarea name="notes" class="w-full rounded-xl border-slate-200" placeholder="Catatan validasi"></textarea><div class="mt-3 flex gap-2"><button name="action" value="approved" class="rounded-xl bg-emerald-600 px-4 py-2 text-sm font-bold text-white">Setujui</button><button name="action" value="revision_requested" class="rounded-xl border border-amber-200 px-4 py-2 text-sm font-bold text-amber-700">Revisi</button><button name="action" value="rejected" class="rounded-xl border border-rose-200 px-4 py-2 text-sm font-bold text-rose-700">Tolak</button></div></form>@endif</section>
@elseif($selectedLogbook)
<a href="{{ $back }}" class="inline-flex rounded-xl border border-slate-200 bg-white px-4 py-2 text-sm font-bold">Kembali ke Daftar</a><section class="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><h2 class="text-2xl font-black">{{ $selectedLogbook->title }}</h2><p class="mt-1 text-sm text-slate-500">{{ $selectedLogbook->entry_date?->format('d M Y') }} · {{ str($selectedLogbook->status)->replace('_', ' ')->headline() }}</p><div class="mt-5 grid gap-3 lg:grid-cols-2"><div class="rounded-xl bg-slate-50 p-4">{{ $selectedLogbook->activity_summary }}</div><div class="rounded-xl bg-slate-50 p-4">{{ $selectedLogbook->learning_outcomes }}</div><div class="rounded-xl bg-slate-50 p-4 lg:col-span-2">{{ $selectedLogbook->reflection }}</div></div><div class="mt-4 space-y-2">@foreach($selectedLogbook->attachments as $attachment)<a href="{{ $attachment->isExternalLink() ? $attachment->previewUrl() : route('field-supervisor.pkpa-logbooks.attachments.download', $attachment) }}" target="_blank" class="flex justify-between rounded-xl border p-3 text-sm font-bold"><span>{{ $attachment->displayLabel() }}</span><span class="text-cyan-700">{{ $attachment->isExternalLink() ? 'Preview Link' : 'Unduh' }}</span></a>@endforeach</div>@if($selectedLogbook->status === 'submitted')<form method="POST" action="{{ route('field-supervisor.pkpa-logbooks.review', $selectedLogbook) }}" class="mt-5">@csrf<textarea name="comments" class="w-full rounded-xl border-slate-200" placeholder="Catatan review"></textarea><div class="mt-3 flex gap-2"><button name="action" value="approved" class="rounded-xl bg-emerald-600 px-4 py-2 text-sm font-bold text-white">Setujui</button><button name="action" value="revision_requested" class="rounded-xl border border-amber-200 px-4 py-2 text-sm font-bold text-amber-700">Revisi</button><button name="action" value="rejected" class="rounded-xl border border-rose-200 px-4 py-2 text-sm font-bold text-rose-700">Tolak</button></div></form>@endif</section>
@else
<section class="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-sky-100"><p class="text-xs font-black uppercase text-cyan-700">{{ $run->practiceDomain?->name }}</p><h2 class="text-2xl font-black">{{ $run->studentDisplayName() }}</h2><p class="text-sm text-slate-500">Klik entri untuk memeriksa detail dan memvalidasi kiriman baru.</p><div class="mt-4 grid gap-3 sm:grid-cols-2"><div class="rounded-xl bg-amber-50 p-3"><p class="text-xs font-black uppercase text-amber-700">Presensi Perlu Validasi</p><p class="mt-1 font-black">{{ $pendingAttendanceCount }}</p></div><div class="rounded-xl bg-amber-50 p-3"><p class="text-xs font-black uppercase text-amber-700">Logbook Perlu Validasi</p><p class="mt-1 font-black">{{ $pendingLogbookCount }}</p></div></div></section>
<section class="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-sky-100"><h3 class="text-lg font-black">Daftar Presensi</h3><div class="mt-3 divide-y">@forelse($attendances as $r)<a href="{{ route('field-supervisor.pkpa-operations.show',['run'=>$run,'attendance'=>$r->id]) }}" class="flex justify-between py-3"><span>{{ $r->attendance_date?->format('d M Y') }} · {{ $r->check_in_time }}-{{ $r->check_out_time }}</span><span class="text-sm font-bold text-cyan-700">{{ $r->submission_status === 'submitted' ? 'Validasi' : 'Lihat Detail' }}</span></a>@empty<p class="py-5 text-sm text-slate-500">Belum ada presensi terkirim.</p>@endforelse</div>{{ $attendances->links() }}</section>
<section class="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-sky-100"><h3 class="text-lg font-black">Daftar Logbook</h3><div class="mt-3 divide-y">@forelse($logbooks as $e)<a href="{{ route('field-supervisor.pkpa-operations.show',['run'=>$run,'logbook'=>$e->id]) }}" class="flex justify-between py-3"><span>{{ $e->entry_date?->format('d M Y') }} · {{ $e->title }}</span><span class="text-sm font-bold text-cyan-700">{{ $e->status === 'submitted' ? 'Validasi' : 'Lihat Detail' }}</span></a>@empty<p class="py-5 text-sm text-slate-500">Belum ada logbook terkirim.</p>@endforelse</div>{{ $logbooks->links() }}</section>
@endif
</div>
@endsection
