@csrf
<div class="grid gap-4 md:grid-cols-2">
    <div><label class="text-xs font-black uppercase tracking-widest text-slate-500">Program</label><select name="pkpa_program_id" class="mt-1 w-full rounded-xl border border-slate-300 px-3 py-2 text-sm" required><option value="">Pilih program</option>@foreach($programs as $program)<option value="{{ $program->id }}" @selected(old('pkpa_program_id', $group->pkpa_program_id) == $program->id)>{{ $program->code }} - {{ $program->name }}</option>@endforeach</select></div>
    <div><label class="text-xs font-black uppercase tracking-widest text-slate-500">Kode</label><input name="code" value="{{ old('code', $group->code) }}" placeholder="KEL-01" class="mt-1 w-full rounded-xl border border-slate-300 px-3 py-2 text-sm" required></div>
    <div><label class="text-xs font-black uppercase tracking-widest text-slate-500">Nama</label><input name="name" value="{{ old('name', $group->name) }}" placeholder="Kelompok 01" class="mt-1 w-full rounded-xl border border-slate-300 px-3 py-2 text-sm" required></div>
    <div><label class="text-xs font-black uppercase tracking-widest text-slate-500">Kapasitas Maksimal</label><input type="number" min="1" name="maximum_members" value="{{ old('maximum_members', $group->maximum_members) }}" class="mt-1 w-full rounded-xl border border-slate-300 px-3 py-2 text-sm"></div>
    <div><label class="text-xs font-black uppercase tracking-widest text-slate-500">Status</label><select name="status" class="mt-1 w-full rounded-xl border border-slate-300 px-3 py-2 text-sm">@foreach(\App\Models\PkpaStudentGroup::STATUSES as $status)<option value="{{ $status }}" @selected(old('status', $group->status ?: 'active') === $status)>{{ str($status)->headline() }}</option>@endforeach</select></div>
    <div class="flex items-end"><label class="flex items-center gap-2 rounded-xl border border-slate-200 px-4 py-3 text-sm font-bold"><input type="hidden" name="is_active" value="0"><input type="checkbox" name="is_active" value="1" @checked(old('is_active', $group->is_active ?? true))> Aktif</label></div>
</div>
<div class="mt-4"><label class="text-xs font-black uppercase tracking-widest text-slate-500">Deskripsi</label><textarea name="description" rows="3" class="mt-1 w-full rounded-xl border border-slate-300 px-3 py-2 text-sm">{{ old('description', $group->description) }}</textarea></div>
<div class="mt-5 flex flex-wrap gap-2"><button class="rounded-xl bg-cyan-700 px-4 py-2 text-sm font-black text-white">Simpan</button><a href="{{ route('management.pkpa-student-groups.index') }}" class="rounded-xl border border-slate-300 px-4 py-2 text-sm font-bold">Batal</a></div>
