<?php

use App\Http\Controllers\Admin\UserImportController;
use App\Http\Controllers\Admin\UserManagementController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\Examiner\ExamScheduleController as ExaminerExamScheduleController;
use App\Http\Controllers\Examiner\AssessmentController as ExaminerAssessmentController;
use App\Http\Controllers\HealthController;
use App\Http\Controllers\FieldSupervisor\AssessmentController as FieldAssessmentController;
use App\Http\Controllers\FieldSupervisor\CompetencyController as FieldCompetencyController;
use App\Http\Controllers\FieldSupervisor\FinalReportReviewController as FieldFinalReportReviewController;
use App\Http\Controllers\FieldSupervisor\FieldStudentController;
use App\Http\Controllers\FieldSupervisor\LogbookValidationController;
use App\Http\Controllers\FieldSupervisor\PkpaScheduleController as FieldPkpaScheduleController;
use App\Http\Controllers\FieldSupervisor\PkpaRotationOperationController as FieldPkpaRotationOperationController;
use App\Http\Controllers\FieldSupervisor\PkpaAcademicRotationController as FieldPkpaAcademicRotationController;
use App\Http\Controllers\FieldSupervisor\PkpaAssessmentController as FieldPkpaAssessmentController;
use App\Http\Controllers\FieldSupervisor\PkpaPortfolioReviewController as FieldPkpaPortfolioReviewController;
use App\Http\Controllers\InternalSupervisor\ExamScheduleController as InternalExamScheduleController;
use App\Http\Controllers\InternalSupervisor\AssessmentController as InternalAssessmentController;
use App\Http\Controllers\InternalSupervisor\CompetencyController as InternalCompetencyController;
use App\Http\Controllers\InternalSupervisor\FinalReportReviewController;
use App\Http\Controllers\InternalSupervisor\LogbookMonitoringController as InternalLogbookMonitoringController;
use App\Http\Controllers\InternalSupervisor\PkpaScheduleController as InternalPkpaScheduleController;
use App\Http\Controllers\InternalSupervisor\PkpaRotationOperationController as InternalPkpaRotationOperationController;
use App\Http\Controllers\InternalSupervisor\PkpaAcademicRotationController as InternalPkpaAcademicRotationController;
use App\Http\Controllers\InternalSupervisor\PkpaAssessmentController as InternalPkpaAssessmentController;
use App\Http\Controllers\InternalSupervisor\PkpaPortfolioReviewController as InternalPkpaPortfolioReviewController;
use App\Http\Controllers\InternalSupervisor\SupervisedStudentController;
use App\Http\Controllers\Management\KpAssignmentController;
use App\Http\Controllers\Management\KpAssignmentLogController;
use App\Http\Controllers\Management\KpCompetencyController;
use App\Http\Controllers\Management\KpPeriodController;
use App\Http\Controllers\Management\KpPlaceController;
use App\Http\Controllers\Management\KpPlaceQuotaController;
use App\Http\Controllers\Management\KpDocumentRequirementController;
use App\Http\Controllers\Management\KpRegistrationReviewController;
use App\Http\Controllers\Management\KpQuotaLogController;
use App\Http\Controllers\Management\FinalReportLogController;
use App\Http\Controllers\Management\FinalReportMonitoringController;
use App\Http\Controllers\Management\ExamLogController;
use App\Http\Controllers\Management\ExamRequestController as ManagementExamRequestController;
use App\Http\Controllers\Management\ExamScheduleController as ManagementExamScheduleController;
use App\Http\Controllers\Management\ExternalDocumentReferenceController;
use App\Http\Controllers\Management\ExportController;
use App\Http\Controllers\Management\IntegrationReviewController;
use App\Http\Controllers\Management\AssessmentComponentController;
use App\Http\Controllers\Management\LogbookLogController;
use App\Http\Controllers\Management\LogbookMonitoringController;
use App\Http\Controllers\Management\OrientationTestResultController;
use App\Http\Controllers\Management\PlaceSelectionMonitoringController;
use App\Http\Controllers\Management\PkpaPracticeDomainController;
use App\Http\Controllers\Management\PkpaPracticeSiteController;
use App\Http\Controllers\Management\PkpaProgramController;
use App\Http\Controllers\Management\PkpaEnrollmentController;
use App\Http\Controllers\Management\PkpaInternalSupervisorController;
use App\Http\Controllers\Management\PkpaPlacementPlannerController;
use App\Http\Controllers\Management\PkpaPlacementPublicationController;
use App\Http\Controllers\Management\PkpaPlacementReadinessController;
use App\Http\Controllers\Management\PkpaProgramSiteController;
use App\Http\Controllers\Management\PkpaRotationOperationController as ManagementPkpaRotationOperationController;
use App\Http\Controllers\Management\PkpaAcademicRotationController as ManagementPkpaAcademicRotationController;
use App\Http\Controllers\Management\PkpaAssessmentController as ManagementPkpaAssessmentController;
use App\Http\Controllers\Management\PkpaAnalyticsController;
use App\Http\Controllers\Management\PkpaCoreDirectoryController;
use App\Http\Controllers\Management\PkpaDocumentController;
use App\Http\Controllers\Management\PkpaFinalProgramController;
use App\Http\Controllers\Management\PkpaPortfolioBuilderController;
use App\Http\Controllers\Management\PkpaStudentGroupController;
use App\Http\Controllers\Management\SelectionLogController;
use App\Http\Controllers\Management\ScoreLogController;
use App\Http\Controllers\Management\ScoreMonitoringController;
use App\Http\Controllers\Management\RecapController;
use App\Http\Controllers\Management\WaitingListController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\RoleSelectionController;
use App\Http\Controllers\Student\KpDocumentUploadController;
use App\Http\Controllers\Student\KpDocumentController;
use App\Http\Controllers\Student\KpRegistrationController;
use App\Http\Controllers\Student\AssignmentController;
use App\Http\Controllers\Student\ExamRequestController as StudentExamRequestController;
use App\Http\Controllers\Student\FinalReportController;
use App\Http\Controllers\Student\LogbookController;
use App\Http\Controllers\Student\OrientationTestController;
use App\Http\Controllers\Student\PlaceSelectionController;
use App\Http\Controllers\Student\PkpaScheduleController as StudentPkpaScheduleController;
use App\Http\Controllers\Student\PkpaRotationOperationController as StudentPkpaRotationOperationController;
use App\Http\Controllers\Student\PkpaAcademicRotationController as StudentPkpaAcademicRotationController;
use App\Http\Controllers\Student\PkpaDocumentPortalController;
use App\Http\Controllers\Student\PkpaGradeController as StudentPkpaGradeController;
use App\Http\Controllers\Student\PkpaFinalResultController;
use App\Http\Controllers\Student\PkpaPortfolioController as StudentPkpaPortfolioController;
use App\Http\Controllers\Student\ScoreController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

Route::view('/', 'welcome')->name('landing');
Route::get('/health', [HealthController::class, 'public'])->middleware('throttle:pkpa-health')->name('health.public');

Route::middleware('guest')->group(function () {
    Route::get('/login', [LoginController::class, 'create'])->name('login');
    Route::post('/login', [LoginController::class, 'store'])->name('login.store');
});

Route::post('/logout', [LoginController::class, 'destroy'])
    ->middleware('auth')
    ->name('logout');

Route::middleware(['auth', 'active'])->group(function () {
    Route::get('/pilih-role', [RoleSelectionController::class, 'index'])->name('role.select');
    Route::post('/set-role/{role:name}', [RoleSelectionController::class, 'store'])->name('role.set');
    Route::get('/profile/avatar', [ProfileController::class, 'avatar'])->name('profile.avatar.show');
    Route::get('/profile/core-avatar', [ProfileController::class, 'coreAvatar'])->name('profile.core-avatar.show');

    Route::middleware('role.selected')->group(function () {
        Route::get('/dashboard', [DashboardController::class, 'redirect'])->name('dashboard');
        Route::get('/profil-saya', [ProfileController::class, 'show'])->name('profile.show');
        Route::redirect('/profile', '/profil-saya')->name('profile.alias');
        Route::post('/profile/avatar', [ProfileController::class, 'updateAvatar'])->name('profile.avatar.update');
        Route::delete('/profile/avatar', [ProfileController::class, 'deleteAvatar'])->name('profile.avatar.delete');
        Route::get('/profile/edit', [ProfileController::class, 'edit'])->name('profile.edit');
        Route::post('/profile/sync-core', [ProfileController::class, 'syncCore'])->name('profile.sync-core');
        Route::put('/profile', [ProfileController::class, 'update'])->name('profile.update');
        Route::get('/admin/health', [HealthController::class, 'admin'])->middleware('throttle:pkpa-health')->name('health.admin');

        Route::middleware(['role:admin', 'local.accounts.enabled'])->prefix('admin')->name('admin.')->group(function () {
            Route::post('users/sync-core', [UserManagementController::class, 'bulkSyncFromCore'])->name('users.sync-core');
            Route::resource('users', UserManagementController::class);
            Route::post('users/{user}/sync-core', [UserManagementController::class, 'syncFromCore'])->name('users.sync-core.single');
            Route::post('users/{user}/reset-password', [UserManagementController::class, 'resetPassword'])->name('users.reset-password');
            Route::post('users/{user}/toggle-status', [UserManagementController::class, 'toggleStatus'])->name('users.toggle-status');

            Route::get('import-users', [UserImportController::class, 'index'])->name('import-users.index');
            Route::post('import-users/preview', [UserImportController::class, 'preview'])->name('import-users.preview');
            Route::post('import-users/process', [UserImportController::class, 'process'])->name('import-users.process');
            Route::get('import-users/history', [UserImportController::class, 'history'])->name('import-users.history');
            Route::get('import-users/history/{batch}', [UserImportController::class, 'show'])->name('import-users.history.show');
            Route::get('import-users/template/{type}', [UserImportController::class, 'template'])->name('import-users.template');
        });

        Route::middleware('role:admin,koordinator_kp')->prefix('management')->name('management.')->group(function () {
            Route::get('core-directory/lecturers', [PkpaCoreDirectoryController::class, 'lecturers'])->name('core-directory.lecturers');
            Route::get('core-directory/field-supervisors', [PkpaCoreDirectoryController::class, 'fieldSupervisors'])->name('core-directory.field-supervisors');
            Route::get('core-directory/students', [PkpaCoreDirectoryController::class, 'students'])->name('core-directory.students');
            Route::get('pkpa-enrollments/import/template', [PkpaEnrollmentController::class, 'template'])->name('pkpa-enrollments.import.template');
            Route::get('pkpa-enrollments/import', [PkpaEnrollmentController::class, 'importForm'])->name('pkpa-enrollments.import');
            Route::post('pkpa-enrollments/import/preview', [PkpaEnrollmentController::class, 'importPreview'])->name('pkpa-enrollments.import.preview');
            Route::get('pkpa-enrollment-imports/{batch}', [PkpaEnrollmentController::class, 'importShow'])->name('pkpa-enrollment-imports.show');
            Route::post('pkpa-enrollment-imports/{batch}/run', [PkpaEnrollmentController::class, 'importRun'])->name('pkpa-enrollment-imports.run');
            Route::get('pkpa-placement-readiness', [PkpaPlacementReadinessController::class, 'index'])->name('pkpa-placement-readiness.index');
            Route::get('pkpa-operations', [ManagementPkpaRotationOperationController::class, 'index'])->name('pkpa-operations.index');
            Route::get('pkpa-academics', [ManagementPkpaAcademicRotationController::class, 'index'])->name('pkpa-academics.index');
            Route::get('pkpa-academics/export', [ManagementPkpaAcademicRotationController::class, 'export'])->name('pkpa-academics.export');
            Route::get('pkpa-assessments', [ManagementPkpaAssessmentController::class, 'index'])->name('pkpa-assessments.index');
            Route::get('pkpa-assessments/export', [ManagementPkpaAssessmentController::class, 'export'])->name('pkpa-assessments.export');
            Route::get('pkpa-final-program', [PkpaFinalProgramController::class, 'index'])->name('pkpa-final-program.index');
            Route::get('pkpa-final-program/export', [PkpaFinalProgramController::class, 'export'])->name('pkpa-final-program.export');
            Route::get('pkpa-documents', [PkpaDocumentController::class, 'index'])->name('pkpa-documents.index');
            Route::get('pkpa-documents/export', [PkpaDocumentController::class, 'exportCsv'])->middleware('throttle:pkpa-exports')->name('pkpa-documents.export');
            Route::post('pkpa-document-types', [PkpaDocumentController::class, 'storeType'])->name('pkpa-document-types.store');
            Route::post('pkpa-document-types/{type}/templates', [PkpaDocumentController::class, 'storeTemplate'])->name('pkpa-document-types.templates.store');
            Route::post('pkpa-document-templates/{template}/activate', [PkpaDocumentController::class, 'activateTemplate'])->name('pkpa-document-templates.activate');
            Route::post('pkpa-document-types/{type}/numbering', [PkpaDocumentController::class, 'storeNumbering'])->name('pkpa-document-types.numbering.store');
            Route::post('pkpa-document-types/{type}/signatories', [PkpaDocumentController::class, 'storeSignatory'])->name('pkpa-document-types.signatories.store');
            Route::post('pkpa-document-types/{type}/generate', [PkpaDocumentController::class, 'generateDraft'])->name('pkpa-document-types.generate');
            Route::post('pkpa-documents/{document}/approve', [PkpaDocumentController::class, 'approve'])->name('pkpa-documents.approve');
            Route::post('pkpa-documents/{document}/publish', [PkpaDocumentController::class, 'publish'])->name('pkpa-documents.publish');
            Route::post('pkpa-documents/{document}/cancel', [PkpaDocumentController::class, 'cancel'])->name('pkpa-documents.cancel');
            Route::get('pkpa-document-versions/{version}/download', [PkpaDocumentController::class, 'download'])->middleware('throttle:pkpa-downloads')->name('pkpa-document-versions.download');
            Route::get('pkpa-analytics', [PkpaAnalyticsController::class, 'index'])->name('pkpa-analytics.index');
            Route::get('pkpa-analytics/export', [PkpaAnalyticsController::class, 'export'])->middleware('throttle:pkpa-exports')->name('pkpa-analytics.export');
            Route::get('pkpa-portfolios', [PkpaPortfolioBuilderController::class, 'index'])->name('pkpa-portfolios.index');
            Route::post('pkpa-rotation-runs/{run}/portfolio', [PkpaPortfolioBuilderController::class, 'ensure'])->name('pkpa-rotation-runs.portfolio.ensure');
            Route::post('pkpa-portfolios/{portfolio}/reopen', [PkpaPortfolioBuilderController::class, 'reopen'])->name('pkpa-portfolios.reopen');
            Route::post('pkpa-portfolios/{portfolio}/publish', [PkpaPortfolioBuilderController::class, 'publish'])->name('pkpa-portfolios.publish');
            Route::post('pkpa-portfolios/{portfolio}/exports/{format}', [PkpaPortfolioBuilderController::class, 'export'])->name('pkpa-portfolios.exports.store');
            Route::get('pkpa-portfolio-exports/{version}/download', [PkpaPortfolioBuilderController::class, 'download'])->middleware('throttle:pkpa-downloads')->name('pkpa-portfolios.exports.download');
            Route::post('pkpa-programs/{program}/final-schemes', [PkpaFinalProgramController::class, 'storeScheme'])->name('pkpa-final-schemes.store');
            Route::post('pkpa-final-schemes/{scheme}/components', [PkpaFinalProgramController::class, 'storeComponent'])->name('pkpa-final-components.store');
            Route::post('pkpa-final-schemes/{scheme}/activate', [PkpaFinalProgramController::class, 'activateScheme'])->name('pkpa-final-schemes.activate');
            Route::post('pkpa-requirements/{requirement}/completion/evaluate', [PkpaFinalProgramController::class, 'evaluateRequirement'])->name('pkpa-requirements.completion.evaluate');
            Route::post('pkpa-requirements/{requirement}/completion/complete', [PkpaFinalProgramController::class, 'completeRequirement'])->name('pkpa-requirements.completion.complete');
            Route::post('pkpa-enrollments/{enrollment}/final-calculation', [PkpaFinalProgramController::class, 'calculate'])->name('pkpa-final-calculations.store');
            Route::post('pkpa-final-calculations/{calculation}/finalize', [PkpaFinalProgramController::class, 'finalize'])->name('pkpa-final-calculations.finalize');
            Route::post('pkpa-enrollments/{enrollment}/final-results/{result}/decision', [PkpaFinalProgramController::class, 'decide'])->name('pkpa-graduation-decisions.store');
            Route::post('pkpa-final-results/{result}/release', [PkpaFinalProgramController::class, 'release'])->name('pkpa-final-results.release');
            Route::post('pkpa-enrollments/{enrollment}/remedials', [PkpaFinalProgramController::class, 'remedial'])->name('pkpa-remedials.store');
            Route::post('pkpa-program-domains/{programDomain}/assessment-schemes', [ManagementPkpaAssessmentController::class, 'storeScheme'])->name('pkpa-assessment-schemes.store');
            Route::post('pkpa-assessment-schemes/{scheme}/components', [ManagementPkpaAssessmentController::class, 'storeComponent'])->name('pkpa-assessment-components.store');
            Route::post('pkpa-assessment-components/{component}/rubrics', [ManagementPkpaAssessmentController::class, 'storeRubric'])->name('pkpa-assessment-rubrics.store');
            Route::post('pkpa-assessment-rubrics/{rubric}/criteria', [ManagementPkpaAssessmentController::class, 'storeCriterion'])->name('pkpa-assessment-criteria.store');
            Route::post('pkpa-assessment-criteria/{criterion}/levels', [ManagementPkpaAssessmentController::class, 'storeLevel'])->name('pkpa-assessment-levels.store');
            Route::post('pkpa-assessment-schemes/{scheme}/activate', [ManagementPkpaAssessmentController::class, 'activateScheme'])->name('pkpa-assessment-schemes.activate');
            Route::post('pkpa-rotation-runs/{run}/assessment', [ManagementPkpaAssessmentController::class, 'createAssessment'])->name('pkpa-rotation-assessments.store');
            Route::post('pkpa-rotation-assessments/{assessment}/moderate', [ManagementPkpaAssessmentController::class, 'moderate'])->name('pkpa-rotation-assessments.moderate');
            Route::post('pkpa-rotation-assessments/{assessment}/finalize', [ManagementPkpaAssessmentController::class, 'finalize'])->name('pkpa-rotation-assessments.finalize');
            Route::post('pkpa-grade-results/{result}/release', [ManagementPkpaAssessmentController::class, 'release'])->name('pkpa-grade-results.release');
            Route::post('pkpa-grade-releases/{release}/withdraw', [ManagementPkpaAssessmentController::class, 'withdraw'])->name('pkpa-grade-releases.withdraw');
            Route::post('pkpa-program-domains/{programDomain}/competency-sets', [ManagementPkpaAcademicRotationController::class, 'storeCompetencySet'])->name('pkpa-competency-sets.store');
            Route::post('pkpa-competency-sets/{set}/items', [ManagementPkpaAcademicRotationController::class, 'storeCompetencyItem'])->name('pkpa-competency-items.store');
            Route::post('pkpa-competency-sets/{set}/activate', [ManagementPkpaAcademicRotationController::class, 'activateCompetencySet'])->name('pkpa-competency-sets.activate');
            Route::post('pkpa-program-domains/{programDomain}/special-task-templates', [ManagementPkpaAcademicRotationController::class, 'storeTaskTemplate'])->name('pkpa-special-task-templates.store');
            Route::post('pkpa-program-domains/{programDomain}/rotation-report-templates', [ManagementPkpaAcademicRotationController::class, 'storeReportTemplate'])->name('pkpa-rotation-report-templates.store');
            Route::post('pkpa-rotation-runs/{run}/competency-checklist', [ManagementPkpaAcademicRotationController::class, 'ensureChecklist'])->name('pkpa-rotation-runs.competency-checklist');
            Route::post('pkpa-rotation-runs/{run}/special-tasks', [ManagementPkpaAcademicRotationController::class, 'assignTasks'])->name('pkpa-rotation-runs.special-tasks');
            Route::post('pkpa-rotation-runs/{run}/academic-readiness', [ManagementPkpaAcademicRotationController::class, 'readiness'])->name('pkpa-rotation-runs.academic-readiness');
            Route::get('pkpa-operations/export', [ManagementPkpaRotationOperationController::class, 'export'])->name('pkpa-operations.export');
            Route::post('pkpa-publications/{publication}/rotation-runs', [ManagementPkpaRotationOperationController::class, 'createFromPublication'])->name('pkpa-publications.rotation-runs.store');
            Route::post('pkpa-publications/{publication}/sync-operations', [ManagementPkpaRotationOperationController::class, 'syncPublication'])->name('pkpa-publications.operations.sync');
            Route::post('pkpa-program-domains/{programDomain}/operation-rule', [ManagementPkpaRotationOperationController::class, 'saveRule'])->name('pkpa-program-domains.operation-rule.store');
            Route::post('pkpa-rotation-runs/{run}/activate', [ManagementPkpaRotationOperationController::class, 'activate'])->name('pkpa-rotation-runs.activate');
            Route::post('pkpa-rotation-runs/{run}/hold', [ManagementPkpaRotationOperationController::class, 'hold'])->name('pkpa-rotation-runs.hold');
            Route::post('pkpa-rotation-runs/{run}/resume', [ManagementPkpaRotationOperationController::class, 'resume'])->name('pkpa-rotation-runs.resume');
            Route::post('pkpa-rotation-runs/{run}/snapshot', [ManagementPkpaRotationOperationController::class, 'snapshot'])->name('pkpa-rotation-runs.snapshot');
            Route::post('pkpa-rotation-runs/{run}/complete', [ManagementPkpaRotationOperationController::class, 'complete'])->name('pkpa-rotation-runs.complete');
            Route::get('pkpa-publications', [PkpaPlacementPublicationController::class, 'index'])->name('pkpa-publications.index');
            Route::get('pkpa-placement-plans/{plan}/final-review', [PkpaPlacementPublicationController::class, 'review'])->name('pkpa-placement-plans.final-review');
            Route::post('pkpa-placement-plans/{plan}/publication-lock', [PkpaPlacementPublicationController::class, 'lock'])->name('pkpa-placement-plans.publication-lock');
            Route::post('pkpa-placement-plans/{plan}/publish', [PkpaPlacementPublicationController::class, 'publish'])->name('pkpa-placement-plans.publish');
            Route::get('pkpa-publications/{publication}', [PkpaPlacementPublicationController::class, 'show'])->name('pkpa-publications.show');
            Route::post('pkpa-publications/{publication}/withdraw', [PkpaPlacementPublicationController::class, 'withdraw'])->name('pkpa-publications.withdraw');
            Route::get('pkpa-publications/{publication}/export', [PkpaPlacementPublicationController::class, 'export'])->name('pkpa-publications.export');
            Route::post('pkpa-notification-deliveries/retry', [PkpaPlacementPublicationController::class, 'retryNotifications'])->name('pkpa-notifications.retry');
            Route::get('pkpa-publications/{publication}/change-requests/create', [PkpaPlacementPublicationController::class, 'createChange'])->name('pkpa-change-requests.create');
            Route::post('pkpa-publications/{publication}/change-requests', [PkpaPlacementPublicationController::class, 'storeChange'])->name('pkpa-change-requests.store');
            Route::get('pkpa-change-requests/{changeRequest}', [PkpaPlacementPublicationController::class, 'showChange'])->name('pkpa-change-requests.show');
            Route::post('pkpa-change-requests/{changeRequest}/submit', [PkpaPlacementPublicationController::class, 'submitChange'])->name('pkpa-change-requests.submit');
            Route::post('pkpa-change-requests/{changeRequest}/approve', [PkpaPlacementPublicationController::class, 'approveChange'])->name('pkpa-change-requests.approve');
            Route::post('pkpa-change-requests/{changeRequest}/reject', [PkpaPlacementPublicationController::class, 'rejectChange'])->name('pkpa-change-requests.reject');
            Route::post('pkpa-change-requests/{changeRequest}/apply', [PkpaPlacementPublicationController::class, 'applyChange'])->name('pkpa-change-requests.apply');
            Route::get('pkpa-placement-planner', [PkpaPlacementPlannerController::class, 'index'])->name('pkpa-placement-planner.index');
            Route::post('pkpa-placement-planner/plans', [PkpaPlacementPlannerController::class, 'storePlan'])->name('pkpa-placement-planner.plans.store');
            Route::post('pkpa-placement-plans/{plan}/clone', [PkpaPlacementPlannerController::class, 'clonePlan'])->name('pkpa-placement-plans.clone');
            Route::post('pkpa-placement-plans/{plan}/current', [PkpaPlacementPlannerController::class, 'setCurrent'])->name('pkpa-placement-plans.current');
            Route::post('pkpa-placement-plans/{plan}/lock', [PkpaPlacementPlannerController::class, 'lock'])->name('pkpa-placement-plans.lock');
            Route::post('pkpa-placement-plans/{plan}/assignments', [PkpaPlacementPlannerController::class, 'saveAssignment'])->name('pkpa-placement-plans.assignments.store');
            Route::delete('pkpa-rotation-assignments/{assignment}', [PkpaPlacementPlannerController::class, 'deleteAssignment'])->name('pkpa-rotation-assignments.destroy');
            Route::post('pkpa-placement-plans/{plan}/bulk-preview', [PkpaPlacementPlannerController::class, 'bulkPreview'])->name('pkpa-placement-plans.bulk.preview');
            Route::post('pkpa-placement-batches/{batch}/apply', [PkpaPlacementPlannerController::class, 'bulkApply'])->name('pkpa-placement-batches.apply');
            Route::post('pkpa-placement-batches/{batch}/undo', [PkpaPlacementPlannerController::class, 'bulkUndo'])->name('pkpa-placement-batches.undo');
            Route::post('pkpa-placement-plans/{plan}/validate', [PkpaPlacementPlannerController::class, 'validatePlan'])->name('pkpa-placement-plans.validate');
            Route::get('pkpa-placement-plans/{plan}/timeline', [PkpaPlacementPlannerController::class, 'timeline'])->name('pkpa-placement-plans.timeline');
            Route::get('pkpa-placement-plans/{plan}/export', [PkpaPlacementPlannerController::class, 'export'])->name('pkpa-placement-plans.export');
            Route::get('pkpa-placement-plans/{plan}/options', [PkpaPlacementPlannerController::class, 'options'])->name('pkpa-placement-plans.options');
            Route::post('pkpa-programs/{pkpa_program}/sync-enrollments', [PkpaEnrollmentController::class, 'syncProgram'])->name('pkpa-programs.enrollments.sync');
            Route::get('pkpa-programs/{pkpa_program}/configure', [PkpaProgramController::class, 'configure'])->name('pkpa-programs.configure');
            Route::put('pkpa-programs/{pkpa_program}/configure', [PkpaProgramController::class, 'updateConfiguration'])->name('pkpa-programs.configure.update');
            Route::get('pkpa-programs/{pkpa_program}/readiness', [PkpaProgramController::class, 'readiness'])->name('pkpa-programs.readiness');
            Route::post('pkpa-programs/{pkpa_program}/status', [PkpaProgramController::class, 'status'])->name('pkpa-programs.status');
            Route::resource('pkpa-programs', PkpaProgramController::class);
            Route::post('pkpa-enrollments/{pkpa_enrollment}/sync', [PkpaEnrollmentController::class, 'sync'])->name('pkpa-enrollments.sync');
            Route::post('pkpa-enrollments/{pkpa_enrollment}/status', [PkpaEnrollmentController::class, 'status'])->name('pkpa-enrollments.status');
            Route::post('pkpa-enrollments/{pkpa_enrollment}/cancel', [PkpaEnrollmentController::class, 'cancel'])->name('pkpa-enrollments.cancel');
            Route::resource('pkpa-enrollments', PkpaEnrollmentController::class)->only(['index', 'create', 'store', 'show']);
            Route::post('pkpa-student-groups/{pkpa_student_group}/members', [PkpaStudentGroupController::class, 'addMember'])->name('pkpa-student-groups.members.store');
            Route::post('pkpa-student-groups/{pkpa_student_group}/members/bulk', [PkpaStudentGroupController::class, 'bulkMembers'])->name('pkpa-student-groups.members.bulk');
            Route::delete('pkpa-student-groups/{pkpa_student_group}/members/{member}', [PkpaStudentGroupController::class, 'removeMember'])->name('pkpa-student-groups.members.destroy');
            Route::resource('pkpa-student-groups', PkpaStudentGroupController::class)->except(['destroy']);
            Route::post('pkpa-program-sites/{pkpa_program_site}/deactivate', [PkpaProgramSiteController::class, 'deactivate'])->name('pkpa-program-sites.deactivate');
            Route::post('pkpa-program-sites/{pkpa_program_site}/availability', [PkpaProgramSiteController::class, 'storeAvailability'])->name('pkpa-program-sites.availability.store');
            Route::put('pkpa-program-sites/{pkpa_program_site}/availability/{period}', [PkpaProgramSiteController::class, 'updateAvailability'])->name('pkpa-program-sites.availability.update');
            Route::post('pkpa-program-sites/{pkpa_program_site}/availability/{period}/cancel', [PkpaProgramSiteController::class, 'cancelAvailability'])->name('pkpa-program-sites.availability.cancel');
            Route::post('pkpa-program-sites/{pkpa_program_site}/field-supervisors', [PkpaProgramSiteController::class, 'storeFieldSupervisor'])->name('pkpa-program-sites.field-supervisors.store');
            Route::post('pkpa-program-sites/{pkpa_program_site}/field-supervisors/{supervisor}/sync', [PkpaProgramSiteController::class, 'syncFieldSupervisor'])->name('pkpa-program-sites.field-supervisors.sync');
            Route::post('pkpa-program-sites/{pkpa_program_site}/field-supervisors/{supervisor}/unavailability', [PkpaProgramSiteController::class, 'storeFieldUnavailability'])->name('pkpa-program-sites.field-supervisors.unavailability.store');
            Route::post('pkpa-supervisor-unavailability/{period}/cancel', [PkpaProgramSiteController::class, 'cancelUnavailability'])->name('pkpa-supervisor-unavailability.cancel');
            Route::resource('pkpa-program-sites', PkpaProgramSiteController::class)->only(['index', 'create', 'store', 'show']);
            Route::post('pkpa-internal-supervisors/{eligibility}/sync', [PkpaInternalSupervisorController::class, 'sync'])->name('pkpa-internal-supervisors.sync');
            Route::post('pkpa-internal-supervisors/{eligibility}/deactivate', [PkpaInternalSupervisorController::class, 'deactivate'])->name('pkpa-internal-supervisors.deactivate');
            Route::post('pkpa-internal-supervisors/{eligibility}/unavailability', [PkpaInternalSupervisorController::class, 'storeUnavailability'])->name('pkpa-internal-supervisors.unavailability.store');
            Route::resource('pkpa-internal-supervisors', PkpaInternalSupervisorController::class)->only(['index', 'create', 'store']);
            Route::post('pkpa-practice-domains/{pkpa_practice_domain}/options', [PkpaPracticeDomainController::class, 'storeOption'])->name('pkpa-practice-domains.options.store');
            Route::put('pkpa-practice-domains/{pkpa_practice_domain}/options/{option}', [PkpaPracticeDomainController::class, 'updateOption'])->name('pkpa-practice-domains.options.update');
            Route::delete('pkpa-practice-domains/{pkpa_practice_domain}/options/{option}', [PkpaPracticeDomainController::class, 'deleteOption'])->name('pkpa-practice-domains.options.destroy');
            Route::resource('pkpa-practice-domains', PkpaPracticeDomainController::class);
            Route::resource('pkpa-practice-sites', PkpaPracticeSiteController::class);
            Route::resource('kp-periods', KpPeriodController::class);
            Route::resource('kp-places', KpPlaceController::class);
            Route::resource('kp-place-quotas', KpPlaceQuotaController::class);
            Route::post('kp-place-quotas/{quota}/toggle-open', [KpPlaceQuotaController::class, 'toggleOpen'])->name('kp-place-quotas.toggle-open');
            Route::get('kp-quota-logs', [KpQuotaLogController::class, 'index'])->name('kp-quota-logs.index');
            Route::resource('document-requirements', KpDocumentRequirementController::class)->except(['show']);
            Route::get('pkpa-registrations', [KpRegistrationReviewController::class, 'index'])->name('pkpa-registrations.index');
            Route::get('pkpa-registrations/{registration}', [KpRegistrationReviewController::class, 'show'])->name('pkpa-registrations.show');
            Route::post('pkpa-registrations/{registration}/documents/{document}/approve', [KpRegistrationReviewController::class, 'approveDocument'])->name('pkpa-registrations.documents.approve');
            Route::post('pkpa-registrations/{registration}/documents/{document}/revision', [KpRegistrationReviewController::class, 'revisionDocument'])->name('pkpa-registrations.documents.revision');
            Route::post('pkpa-registrations/{registration}/documents/{document}/reject', [KpRegistrationReviewController::class, 'rejectDocument'])->name('pkpa-registrations.documents.reject');
            Route::post('pkpa-registrations/{registration}/verify', [KpRegistrationReviewController::class, 'verify'])->name('pkpa-registrations.verify');
            Route::post('pkpa-registrations/{registration}/revision', [KpRegistrationReviewController::class, 'revision'])->name('pkpa-registrations.revision');
            Route::post('pkpa-registrations/{registration}/reject', [KpRegistrationReviewController::class, 'reject'])->name('pkpa-registrations.reject');
            Route::get('pkpa-registrations/{registration}/documents/{document}/preview', [KpRegistrationReviewController::class, 'preview'])->name('pkpa-registrations.documents.preview');
            Route::get('pkpa-registrations/{registration}/documents/{document}/download', [KpRegistrationReviewController::class, 'download'])->name('pkpa-registrations.documents.download');
            Route::get('kp-registrations', [KpRegistrationReviewController::class, 'index'])->name('kp-registrations.index');
            Route::get('kp-registrations/{registration}', [KpRegistrationReviewController::class, 'show'])->name('kp-registrations.show');
            Route::post('kp-registrations/{registration}/documents/{document}/approve', [KpRegistrationReviewController::class, 'approveDocument'])->name('kp-registrations.documents.approve');
            Route::post('kp-registrations/{registration}/documents/{document}/revision', [KpRegistrationReviewController::class, 'revisionDocument'])->name('kp-registrations.documents.revision');
            Route::post('kp-registrations/{registration}/documents/{document}/reject', [KpRegistrationReviewController::class, 'rejectDocument'])->name('kp-registrations.documents.reject');
            Route::post('kp-registrations/{registration}/verify', [KpRegistrationReviewController::class, 'verify'])->name('kp-registrations.verify');
            Route::post('kp-registrations/{registration}/revision', [KpRegistrationReviewController::class, 'revision'])->name('kp-registrations.revision');
            Route::post('kp-registrations/{registration}/reject', [KpRegistrationReviewController::class, 'reject'])->name('kp-registrations.reject');
            Route::get('kp-registrations/{registration}/documents/{document}/preview', [KpRegistrationReviewController::class, 'preview'])->name('kp-registrations.documents.preview');
            Route::get('kp-registrations/{registration}/documents/{document}/download', [KpRegistrationReviewController::class, 'download'])->name('kp-registrations.documents.download');

            Route::middleware('student.place-selection.enabled')->group(function () {
                Route::get('place-selections', [PlaceSelectionMonitoringController::class, 'index'])->name('place-selections.index');
                Route::get('place-selections/report/preview', [PlaceSelectionMonitoringController::class, 'reportPreview'])->name('place-selections.report.preview');
                Route::get('place-selections/report/download/{format}', [PlaceSelectionMonitoringController::class, 'reportDownload'])->name('place-selections.report.download');
                Route::get('place-selections/manual', [PlaceSelectionMonitoringController::class, 'manual'])->name('place-selections.manual');
                Route::post('place-selections/manual', [PlaceSelectionMonitoringController::class, 'storeManual'])->name('place-selections.manual.store');
                Route::get('place-selections/{selection}', [PlaceSelectionMonitoringController::class, 'show'])->name('place-selections.show');
                Route::post('place-selections/{selection}/cancel', [PlaceSelectionMonitoringController::class, 'cancel'])->name('place-selections.cancel');
                Route::get('place-selections/{selection}/move', [PlaceSelectionMonitoringController::class, 'move'])->name('place-selections.move');
                Route::post('place-selections/{selection}/move', [PlaceSelectionMonitoringController::class, 'moveStore'])->name('place-selections.move.store');
                Route::get('waiting-lists', [WaitingListController::class, 'index'])->name('waiting-lists.index');
                Route::post('waiting-lists/{waitingList}/cancel', [WaitingListController::class, 'cancel'])->name('waiting-lists.cancel');
                Route::post('place-selections/{selection}/create-assignment', [KpAssignmentController::class, 'createFromSelection'])->name('place-selections.create-assignment');
            });
            Route::get('selection-logs', [SelectionLogController::class, 'index'])->name('selection-logs.index');
            Route::get('pkpa-assignments', [KpAssignmentController::class, 'index'])->name('pkpa-assignments.index');
            Route::get('pkpa-assignment-logs', [KpAssignmentLogController::class, 'index'])->name('pkpa-assignment-logs.index');
            Route::get('pkpa-logbook-monitoring', [LogbookMonitoringController::class, 'index'])->name('pkpa-logbook-monitoring.index');
            Route::get('pkpa-logbook-monitoring/{logbook}', [LogbookMonitoringController::class, 'show'])->name('pkpa-logbook-monitoring.show');
            Route::post('pkpa-logbook-monitoring/{logbook}/comments', [LogbookMonitoringController::class, 'comments'])->name('pkpa-logbook-monitoring.comments');
            Route::get('pkpa-logbook-monitoring/{logbook}/evidence/download', [LogbookMonitoringController::class, 'download'])->name('pkpa-logbook-monitoring.evidence.download');
            Route::get('pkpa-logbook-logs', [LogbookLogController::class, 'index'])->name('pkpa-logbook-logs.index');
            Route::get('pkpa-final-reports', [FinalReportMonitoringController::class, 'index'])->name('pkpa-final-reports.index');
            Route::get('pkpa-final-reports/{report}', [FinalReportMonitoringController::class, 'show'])->name('pkpa-final-reports.show');
            Route::get('pkpa-final-reports/files/{file}/download', [FinalReportMonitoringController::class, 'download'])->name('pkpa-final-reports.files.download');
            Route::get('pkpa-final-report-logs', [FinalReportLogController::class, 'index'])->name('pkpa-final-report-logs.index');
            Route::get('kp-assignments/report/preview', [KpAssignmentController::class, 'reportPreview'])->name('kp-assignments.report.preview');
            Route::get('kp-assignments/report/download/{format}', [KpAssignmentController::class, 'reportDownload'])->name('kp-assignments.report.download');
            Route::resource('kp-assignments', KpAssignmentController::class)->except(['destroy']);
            Route::post('kp-assignments/{assignment}/assign-internal-supervisor', [KpAssignmentController::class, 'assignInternalSupervisor'])->name('kp-assignments.assign-internal-supervisor');
            Route::post('kp-assignments/{assignment}/assign-field-supervisor', [KpAssignmentController::class, 'assignFieldSupervisor'])->name('kp-assignments.assign-field-supervisor');
            Route::post('kp-assignments/{assignment}/cancel', [KpAssignmentController::class, 'cancel'])->name('kp-assignments.cancel');
            Route::get('kp-assignment-logs', [KpAssignmentLogController::class, 'index'])->name('kp-assignment-logs.index');
            Route::get('logbooks', [LogbookMonitoringController::class, 'index'])->name('logbooks.index');
            Route::get('logbooks/{logbook}', [LogbookMonitoringController::class, 'show'])->name('logbooks.show');
            Route::post('logbooks/{logbook}/comments', [LogbookMonitoringController::class, 'comments'])->name('logbooks.comments');
            Route::get('logbooks/{logbook}/evidence/download', [LogbookMonitoringController::class, 'download'])->name('logbooks.evidence.download');
            Route::get('logbook-logs', [LogbookLogController::class, 'index'])->name('logbook-logs.index');
            Route::get('final-reports', [FinalReportMonitoringController::class, 'index'])->name('final-reports.index');
            Route::get('final-reports/{report}', [FinalReportMonitoringController::class, 'show'])->name('final-reports.show');
            Route::get('final-reports/files/{file}/download', [FinalReportMonitoringController::class, 'download'])->name('final-reports.files.download');
            Route::get('final-report-logs', [FinalReportLogController::class, 'index'])->name('final-report-logs.index');
            Route::get('exam-requests', [ManagementExamRequestController::class, 'index'])->name('exam-requests.index');
            Route::get('exam-requests/{examRequest}', [ManagementExamRequestController::class, 'show'])->name('exam-requests.show');
            Route::post('exam-requests/{examRequest}/approve', [ManagementExamRequestController::class, 'approve'])->name('exam-requests.approve');
            Route::post('exam-requests/{examRequest}/revision', [ManagementExamRequestController::class, 'revision'])->name('exam-requests.revision');
            Route::post('exam-requests/{examRequest}/reject', [ManagementExamRequestController::class, 'reject'])->name('exam-requests.reject');
            Route::get('exam-requests/{examRequest}/schedule', [ManagementExamScheduleController::class, 'create'])->name('exam-requests.schedule');
            Route::post('exam-requests/{examRequest}/schedule', [ManagementExamScheduleController::class, 'store'])->name('exam-requests.schedule.store');
            Route::get('exams', [ManagementExamScheduleController::class, 'index'])->name('exams.index');
            Route::get('exams/{exam}', [ManagementExamScheduleController::class, 'show'])->name('exams.show');
            Route::get('exams/{exam}/edit', [ManagementExamScheduleController::class, 'edit'])->name('exams.edit');
            Route::put('exams/{exam}', [ManagementExamScheduleController::class, 'update'])->name('exams.update');
            Route::post('exams/{exam}/cancel', [ManagementExamScheduleController::class, 'cancel'])->name('exams.cancel');
            Route::post('exams/{exam}/complete', [ManagementExamScheduleController::class, 'complete'])->name('exams.complete');
            Route::get('exam-logs', [ExamLogController::class, 'index'])->name('exam-logs.index');
            Route::resource('assessment-components', AssessmentComponentController::class)->except(['show'])->parameters(['assessment-components' => 'component']);
            Route::resource('competencies', KpCompetencyController::class)->except(['show', 'create', 'edit'])->parameters(['competencies' => 'competency']);
            Route::get('orientation-tests', [OrientationTestResultController::class, 'index'])->name('orientation-tests.index');
            Route::get('orientation-tests/{attempt}', [OrientationTestResultController::class, 'show'])->name('orientation-tests.show');
            Route::get('pkpa-exams', [ManagementExamScheduleController::class, 'index'])->name('pkpa-exams.index');
            Route::get('pkpa-exams/{exam}', [ManagementExamScheduleController::class, 'show'])->name('pkpa-exams.show');
            Route::get('pkpa-score-monitoring', [ScoreMonitoringController::class, 'index'])->name('pkpa-score-monitoring.index');
            Route::get('pkpa-score-monitoring/{assignment}', [ScoreMonitoringController::class, 'show'])->name('pkpa-score-monitoring.show');
            Route::post('pkpa-score-monitoring/{assignment}/override', [ScoreMonitoringController::class, 'override'])->name('pkpa-score-monitoring.override');
            Route::post('pkpa-score-monitoring/{assignment}/calculate', [ScoreMonitoringController::class, 'calculate'])->name('pkpa-score-monitoring.calculate');
            Route::post('pkpa-score-monitoring/{assignment}/finalize', [ScoreMonitoringController::class, 'finalize'])->name('pkpa-score-monitoring.finalize');
            Route::post('pkpa-final-scores/{finalScore}/publish', [ScoreMonitoringController::class, 'publish'])->name('pkpa-final-scores.publish');
            Route::post('pkpa-final-scores/{finalScore}/unlock', [ScoreMonitoringController::class, 'unlock'])->name('pkpa-final-scores.unlock');
            Route::get('pkpa-score-logs', [ScoreLogController::class, 'index'])->name('pkpa-score-logs.index');
            Route::get('scores', [ScoreMonitoringController::class, 'index'])->name('scores.index');
            Route::get('scores/{assignment}', [ScoreMonitoringController::class, 'show'])->name('scores.show');
            Route::post('scores/{assignment}/override', [ScoreMonitoringController::class, 'override'])->name('scores.override');
            Route::post('scores/{assignment}/calculate', [ScoreMonitoringController::class, 'calculate'])->name('scores.calculate');
            Route::post('scores/{assignment}/finalize', [ScoreMonitoringController::class, 'finalize'])->name('scores.finalize');
            Route::post('final-scores/{finalScore}/publish', [ScoreMonitoringController::class, 'publish'])->name('final-scores.publish');
            Route::post('final-scores/{finalScore}/unlock', [ScoreMonitoringController::class, 'unlock'])->name('final-scores.unlock');
            Route::get('score-logs', [ScoreLogController::class, 'index'])->name('score-logs.index');
            Route::get('recaps', [RecapController::class, 'index'])->name('recaps.index');
            Route::get('recaps/{type}/preview', [RecapController::class, 'preview'])->name('recaps.preview');
            Route::get('recaps/{type}/download/{format}', [RecapController::class, 'download'])->name('recaps.download');
            Route::get('recaps/students', [RecapController::class, 'students'])->name('recaps.students');
            Route::get('recaps/placements', [RecapController::class, 'placements'])->name('recaps.placements');
            Route::get('recaps/logbooks', [RecapController::class, 'logbooks'])->name('recaps.logbooks');
            Route::get('recaps/exams', [RecapController::class, 'exams'])->name('recaps.exams');
            Route::get('recaps/scores', [RecapController::class, 'scores'])->name('recaps.scores');
            Route::get('exports/{type}', ExportController::class)->name('exports.download');
            Route::get('integration/tu-payload-preview', [IntegrationReviewController::class, 'tuPayloadPreview'])->name('integration.tu-payload-preview');
            Route::get('integration/tu-payload-preview.json', [IntegrationReviewController::class, 'tuPayloadPreviewJson'])->name('integration.tu-payload-preview.json');
            Route::get('integration/safa-public-info-preview', [IntegrationReviewController::class, 'safaPublicInfoPreview'])->name('integration.safa-public-info-preview');
            Route::get('integration/safa-public-info-preview.json', [IntegrationReviewController::class, 'safaPublicInfoPreviewJson'])->name('integration.safa-public-info-preview.json');
            Route::get('integration/external-document-references', [ExternalDocumentReferenceController::class, 'index'])->name('integration.external-document-references.index');
            Route::post('integration/external-document-references/drafts', [ExternalDocumentReferenceController::class, 'storeDrafts'])->name('integration.external-document-references.store-drafts');
            Route::get('integration/external-document-references/{reference}/edit', [ExternalDocumentReferenceController::class, 'edit'])->name('integration.external-document-references.edit');
            Route::patch('integration/external-document-references/{reference}', [ExternalDocumentReferenceController::class, 'update'])->name('integration.external-document-references.update');
        });

        Route::middleware('role:mahasiswa')->prefix('mahasiswa')->name('student.')->group(function () {
            Route::get('pkpa-saya', [StudentPkpaScheduleController::class, 'index'])->name('pkpa-schedule.index');
            Route::get('pkpa-saya/{assignment}', [StudentPkpaScheduleController::class, 'show'])->name('pkpa-schedule.show');
            Route::post('pkpa-saya/{assignment}/acknowledge', [StudentPkpaScheduleController::class, 'acknowledge'])->name('pkpa-schedule.acknowledge');
            Route::get('rotasi-pkpa', [StudentPkpaRotationOperationController::class, 'index'])->name('pkpa-operations.index');
            Route::get('rotasi-pkpa/{run}', [StudentPkpaRotationOperationController::class, 'show'])->name('pkpa-operations.show');
            Route::get('akademik-rotasi', [StudentPkpaAcademicRotationController::class, 'index'])->name('pkpa-academics.index');
            Route::get('nilai-pkpa', [StudentPkpaGradeController::class, 'index'])->name('pkpa-grades.index');
            Route::get('hasil-akhir-pkpa', [PkpaFinalResultController::class, 'index'])->name('pkpa-final-results.index');
            Route::get('dokumen-pkpa', [PkpaDocumentPortalController::class, 'index'])->name('pkpa-documents.index');
            Route::get('dokumen-pkpa/{version}/download', [PkpaDocumentPortalController::class, 'download'])->middleware('throttle:pkpa-downloads')->name('pkpa-documents.download');
            Route::get('portofolio-pkpa', [StudentPkpaPortfolioController::class, 'index'])->name('pkpa-portfolios.index');
            Route::get('portfolio-export-versions/{version}/download', [StudentPkpaPortfolioController::class, 'download'])->middleware('throttle:pkpa-downloads')->name('pkpa-portfolios.exports.download');
            Route::get('portofolio-pkpa/{portfolio}', [StudentPkpaPortfolioController::class, 'show'])->name('pkpa-portfolios.show');
            Route::post('portofolio-pkpa/{portfolio}/pakta-integritas', [StudentPkpaPortfolioController::class, 'acknowledge'])->name('pkpa-portfolios.integrity.acknowledge');
            Route::post('portofolio-pkpa/{portfolio}/studi-kasus', [StudentPkpaPortfolioController::class, 'storeCase'])->name('pkpa-portfolios.cases.store');
            Route::post('portofolio-pkpa/{portfolio}/refleksi', [StudentPkpaPortfolioController::class, 'storeReflection'])->name('pkpa-portfolios.reflections.store');
            Route::post('portofolio-pkpa/{portfolio}/penilaian-diri', [StudentPkpaPortfolioController::class, 'storeSelfAssessment'])->name('pkpa-portfolios.self-assessments.store');
            Route::post('portofolio-pkpa/{portfolio}/dokumentasi', [StudentPkpaPortfolioController::class, 'storeDocumentation'])->name('pkpa-portfolios.documentation.store');
            Route::post('portofolio-pkpa/{portfolio}/submit', [StudentPkpaPortfolioController::class, 'submit'])->name('pkpa-portfolios.submit');
            Route::post('portofolio-pkpa/{portfolio}/submit-pd', [StudentPkpaPortfolioController::class, 'submitToInternal'])->name('pkpa-portfolios.submit-internal');
            Route::post('portofolio-pkpa/{portfolio}/exports/{format}', [StudentPkpaPortfolioController::class, 'export'])->name('pkpa-portfolios.exports.store');
            Route::get('akademik-rotasi/{run}', [StudentPkpaAcademicRotationController::class, 'show'])->name('pkpa-academics.show');
            Route::post('kompetensi-rotasi/{record}/progress', [StudentPkpaAcademicRotationController::class, 'markCompetency'])->name('pkpa-competencies.progress');
            Route::post('kompetensi-rotasi/{record}/evidences', [StudentPkpaAcademicRotationController::class, 'evidence'])->name('pkpa-competencies.evidences.store');
            Route::post('kompetensi-rotasi/{record}/submit', [StudentPkpaAcademicRotationController::class, 'submitCompetency'])->name('pkpa-competencies.submit');
            Route::post('tugas-rotasi/{task}/submit', [StudentPkpaAcademicRotationController::class, 'submitTask'])->name('pkpa-special-tasks.submit');
            Route::post('akademik-rotasi/{run}/report', [StudentPkpaAcademicRotationController::class, 'createReport'])->name('pkpa-rotation-reports.store');
            Route::post('laporan-rotasi/{report}/versions', [StudentPkpaAcademicRotationController::class, 'uploadReport'])->name('pkpa-rotation-reports.versions.store');
            Route::post('laporan-rotasi/{report}/submit', [StudentPkpaAcademicRotationController::class, 'submitReport'])->name('pkpa-rotation-reports.submit');
            Route::get('laporan-rotasi/versions/{version}/download', [StudentPkpaAcademicRotationController::class, 'downloadReport'])->name('pkpa-rotation-reports.versions.download');
            Route::post('bimbingan-rotasi/{session}/acknowledge', [StudentPkpaAcademicRotationController::class, 'acknowledgeGuidance'])->name('pkpa-guidance.acknowledge');
            Route::post('rotasi-pkpa/{run}/presensi', [StudentPkpaRotationOperationController::class, 'saveAttendance'])->name('pkpa-operations.attendance.store');
            Route::post('presensi-pkpa/{record}/submit', [StudentPkpaRotationOperationController::class, 'submitAttendance'])->name('pkpa-attendance.submit');
            Route::post('presensi-pkpa/{record}/corrections', [StudentPkpaRotationOperationController::class, 'requestCorrection'])->name('pkpa-attendance.corrections.store');
            Route::post('rotasi-pkpa/{run}/logbooks', [StudentPkpaRotationOperationController::class, 'saveLogbook'])->name('pkpa-logbooks.store');
            Route::post('logbook-pkpa/{entry}/submit', [StudentPkpaRotationOperationController::class, 'submitLogbook'])->name('pkpa-logbooks.submit');
            Route::post('logbook-pkpa/{entry}/attachments', [StudentPkpaRotationOperationController::class, 'uploadAttachment'])->name('pkpa-logbooks.attachments.store');
            Route::get('logbook-pkpa/attachments/{attachment}/download', [StudentPkpaRotationOperationController::class, 'downloadAttachment'])->name('pkpa-logbooks.attachments.download');
            Route::get('pendaftaran-pkpa', [KpRegistrationController::class, 'index'])->name('pkpa-registrations.index');
            Route::get('berkas-pkpa-administrasi', [KpDocumentController::class, 'index'])->name('pkpa-registration-documents.index');
            Route::get('pendaftaran-pkpa/create', [KpRegistrationController::class, 'create'])->name('pkpa-registrations.create');
            Route::post('pendaftaran-pkpa', [KpRegistrationController::class, 'store'])->name('pkpa-registrations.store');
            Route::get('pendaftaran-pkpa/{registration}', [KpRegistrationController::class, 'show'])->name('pkpa-registrations.show');
            Route::post('pendaftaran-pkpa/{registration}/documents/{requirement}', [KpDocumentUploadController::class, 'store'])->name('pkpa-registrations.documents.store');
            Route::post('pendaftaran-pkpa/{registration}/submit', [KpRegistrationController::class, 'submit'])->name('pkpa-registrations.submit');
            Route::get('pendaftaran-pkpa/{registration}/documents/{document}/download', [KpRegistrationController::class, 'download'])->name('pkpa-registrations.documents.download');
            Route::post('pendaftaran-pkpa/{registration}/cancel', [KpRegistrationController::class, 'cancel'])->name('pkpa-registrations.cancel');
            Route::get('pendaftaran-kp', [KpRegistrationController::class, 'index'])->name('kp-registrations.index');
            Route::get('berkas-kp', [KpDocumentController::class, 'index'])->name('kp-documents.index');
            Route::get('pendaftaran-kp/create', [KpRegistrationController::class, 'create'])->name('kp-registrations.create');
            Route::post('pendaftaran-kp', [KpRegistrationController::class, 'store'])->name('kp-registrations.store');
            Route::get('pendaftaran-kp/{registration}', [KpRegistrationController::class, 'show'])->name('kp-registrations.show');
            Route::post('pendaftaran-kp/{registration}/documents/{requirement}', [KpDocumentUploadController::class, 'store'])->name('kp-registrations.documents.store');
            Route::post('pendaftaran-kp/{registration}/submit', [KpRegistrationController::class, 'submit'])->name('kp-registrations.submit');
            Route::get('pendaftaran-kp/{registration}/documents/{document}/download', [KpRegistrationController::class, 'download'])->name('kp-registrations.documents.download');
            Route::post('pendaftaran-kp/{registration}/cancel', [KpRegistrationController::class, 'cancel'])->name('kp-registrations.cancel');
            Route::middleware('student.place-selection.enabled')->group(function () {
                Route::get('pemilihan-tempat', [PlaceSelectionController::class, 'index'])->name('place-selections.index');
                Route::get('pemilihan-tempat/{period}', [PlaceSelectionController::class, 'show'])->name('place-selections.show');
                Route::post('pemilihan-tempat/{quota}/pilih', [PlaceSelectionController::class, 'select'])->name('place-selections.select');
                Route::post('pemilihan-tempat/daftar-tunggu', [PlaceSelectionController::class, 'joinWaitingList'])->name('place-selections.waiting-list');
            });
            Route::get('penempatan-pkpa', [AssignmentController::class, 'show'])->name('pkpa-placement.show');
            Route::get('jurnal-pkpa', [LogbookController::class, 'index'])->name('pkpa-journals.index');
            Route::get('jurnal-pkpa/create', [LogbookController::class, 'create'])->name('pkpa-journals.create');
            Route::post('jurnal-pkpa', [LogbookController::class, 'store'])->name('pkpa-journals.store');
            Route::get('jurnal-pkpa/{logbook}', [LogbookController::class, 'show'])->name('pkpa-journals.show');
            Route::get('jurnal-pkpa/{logbook}/edit', [LogbookController::class, 'edit'])->name('pkpa-journals.edit');
            Route::put('jurnal-pkpa/{logbook}', [LogbookController::class, 'update'])->name('pkpa-journals.update');
            Route::post('jurnal-pkpa/{logbook}/submit', [LogbookController::class, 'submit'])->name('pkpa-journals.submit');
            Route::get('jurnal-pkpa/{logbook}/evidence/download', [LogbookController::class, 'download'])->name('pkpa-journals.evidence.download');
            Route::delete('jurnal-pkpa/{logbook}', [LogbookController::class, 'destroy'])->name('pkpa-journals.destroy');
            Route::get('laporan-pkpa', [FinalReportController::class, 'show'])->name('pkpa-final-report.show');
            Route::post('laporan-pkpa/upload', [FinalReportController::class, 'upload'])->name('pkpa-final-report.upload');
            Route::post('laporan-pkpa/link-final', [FinalReportController::class, 'saveFinalLink'])->name('pkpa-final-report.final-link');
            Route::post('laporan-pkpa/bimbingan', [FinalReportController::class, 'storeGuidance'])->name('pkpa-final-report.guidance.store');
            Route::post('laporan-pkpa/submit', [FinalReportController::class, 'submit'])->name('pkpa-final-report.submit');
            Route::get('laporan-pkpa/files/{file}/download', [FinalReportController::class, 'download'])->name('pkpa-final-report.files.download');
            Route::get('ujian-pkpa', [StudentExamRequestController::class, 'index'])->name('pkpa-exams.index');
            Route::post('ujian-pkpa/ajukan', [StudentExamRequestController::class, 'submit'])->name('pkpa-exams.submit');
            Route::post('ujian-pkpa/batalkan-pengajuan', [StudentExamRequestController::class, 'cancel'])->name('pkpa-exams.cancel');
            Route::get('penempatan-kp', [AssignmentController::class, 'show'])->name('assignments.show');
            Route::get('logbook', [LogbookController::class, 'index'])->name('logbooks.index');
            Route::post('logbook/periode-kerja', [LogbookController::class, 'updateWorkPeriod'])->name('logbooks.work-period.update');
            Route::get('logbook/create', [LogbookController::class, 'create'])->name('logbooks.create');
            Route::post('logbook', [LogbookController::class, 'store'])->name('logbooks.store');
            Route::get('logbook/{logbook}', [LogbookController::class, 'show'])->name('logbooks.show');
            Route::get('logbook/{logbook}/edit', [LogbookController::class, 'edit'])->name('logbooks.edit');
            Route::put('logbook/{logbook}', [LogbookController::class, 'update'])->name('logbooks.update');
            Route::post('logbook/{logbook}/submit', [LogbookController::class, 'submit'])->name('logbooks.submit');
            Route::get('logbook/{logbook}/evidence/download', [LogbookController::class, 'download'])->name('logbooks.evidence.download');
            Route::delete('logbook/{logbook}', [LogbookController::class, 'destroy'])->name('logbooks.destroy');
            Route::get('laporan-akhir', [FinalReportController::class, 'show'])->name('final-reports.show');
            Route::post('laporan-akhir/upload', [FinalReportController::class, 'upload'])->name('final-reports.upload');
            Route::post('laporan-akhir/link-final', [FinalReportController::class, 'saveFinalLink'])->name('final-reports.final-link');
            Route::post('laporan-akhir/bimbingan', [FinalReportController::class, 'storeGuidance'])->name('final-reports.guidance.store');
            Route::post('laporan-akhir/submit', [FinalReportController::class, 'submit'])->name('final-reports.submit');
            Route::get('laporan-akhir/files/{file}/download', [FinalReportController::class, 'download'])->name('final-reports.files.download');
            Route::get('sidang', [StudentExamRequestController::class, 'index'])->name('exams.index');
            Route::post('sidang/ajukan', [StudentExamRequestController::class, 'submit'])->name('exams.submit');
            Route::post('sidang/batalkan-pengajuan', [StudentExamRequestController::class, 'cancel'])->name('exams.cancel');
            Route::get('pre-post-test', [OrientationTestController::class, 'index'])->name('orientation-tests.index');
            Route::get('pre-post-test/hasil/{attempt}', [OrientationTestController::class, 'result'])->name('orientation-tests.result');
            Route::get('pre-post-test/{test}', [OrientationTestController::class, 'show'])->name('orientation-tests.show');
            Route::post('pre-post-test/{test}', [OrientationTestController::class, 'submit'])->name('orientation-tests.submit');
            Route::get('nilai', [ScoreController::class, 'show'])->name('scores.show');
        });

        Route::middleware('role:pembimbing_dalam')->prefix('pembimbing-dalam')->name('internal-supervisor.')->group(function () {
            Route::get('jadwal-pkpa', [InternalPkpaScheduleController::class, 'index'])->name('pkpa-schedule.index');
            Route::get('jadwal-pkpa/{assignment}', [InternalPkpaScheduleController::class, 'show'])->name('pkpa-schedule.show');
            Route::post('jadwal-pkpa/{assignment}/acknowledge', [InternalPkpaScheduleController::class, 'acknowledge'])->name('pkpa-schedule.acknowledge');
            Route::get('monitoring-pkpa', [InternalPkpaRotationOperationController::class, 'index'])->name('pkpa-operations.index');
            Route::get('akademik-pkpa', [InternalPkpaAcademicRotationController::class, 'index'])->name('pkpa-academics.index');
            Route::get('penilaian-pkpa', [InternalPkpaAssessmentController::class, 'index'])->name('pkpa-assessments.index');
            Route::get('review-portofolio', [InternalPkpaPortfolioReviewController::class, 'index'])->name('pkpa-portfolios.index');
            Route::get('review-portofolio/{portfolio}', [InternalPkpaPortfolioReviewController::class, 'show'])->name('pkpa-portfolios.show');
            Route::post('review-portofolio/{portfolio}/approve', [InternalPkpaPortfolioReviewController::class, 'approve'])->name('pkpa-portfolios.approve');
            Route::post('review-portofolio/{portfolio}/revision', [InternalPkpaPortfolioReviewController::class, 'revision'])->name('pkpa-portfolios.revision');
            Route::post('penilaian-pkpa/scores/{score}/save', [InternalPkpaAssessmentController::class, 'save'])->name('pkpa-assessments.scores.save');
            Route::post('penilaian-pkpa/scores/{score}/submit', [InternalPkpaAssessmentController::class, 'submit'])->name('pkpa-assessments.scores.submit');
            Route::post('kompetensi-rotasi/{record}/monitoring', [InternalPkpaAcademicRotationController::class, 'commentCompetency'])->name('pkpa-competencies.monitoring');
            Route::post('tugas-rotasi-submissions/{submission}/review', [InternalPkpaAcademicRotationController::class, 'reviewTask'])->name('pkpa-special-tasks.review');
            Route::post('laporan-rotasi/{report}/review', [InternalPkpaAcademicRotationController::class, 'reviewReport'])->name('pkpa-rotation-reports.review');
            Route::post('akademik-pkpa/{run}/guidance', [InternalPkpaAcademicRotationController::class, 'guidance'])->name('pkpa-guidance.store');
            Route::get('monitoring-pkpa/{run}', [InternalPkpaRotationOperationController::class, 'show'])->name('pkpa-operations.show');
            Route::post('logbook-operasional/{entry}/monitoring', [InternalPkpaRotationOperationController::class, 'reviewLogbook'])->name('pkpa-logbooks.monitoring');
            Route::get('logbook-operasional/attachments/{attachment}/download', [InternalPkpaRotationOperationController::class, 'downloadAttachment'])->name('pkpa-logbooks.attachments.download');
            Route::get('mahasiswa-pkpa', [SupervisedStudentController::class, 'index'])->name('pkpa-students.index');
            Route::get('mahasiswa-pkpa/{assignment}', [SupervisedStudentController::class, 'show'])->name('pkpa-students.show');
            Route::get('jurnal-pkpa', [InternalLogbookMonitoringController::class, 'index'])->name('pkpa-journals.index');
            Route::get('jurnal-pkpa/{logbook}', [InternalLogbookMonitoringController::class, 'show'])->name('pkpa-journals.show');
            Route::post('jurnal-pkpa/{logbook}/comments', [InternalLogbookMonitoringController::class, 'comments'])->name('pkpa-journals.comments');
            Route::get('jurnal-pkpa/{logbook}/evidence/download', [InternalLogbookMonitoringController::class, 'download'])->name('pkpa-journals.evidence.download');
            Route::get('laporan-pkpa', [FinalReportReviewController::class, 'index'])->name('pkpa-final-reports.index');
            Route::get('laporan-pkpa/{report}', [FinalReportReviewController::class, 'show'])->name('pkpa-final-reports.show');
            Route::post('laporan-pkpa/{report}/approve', [FinalReportReviewController::class, 'approve'])->name('pkpa-final-reports.approve');
            Route::post('laporan-pkpa/{report}/revision', [FinalReportReviewController::class, 'revision'])->name('pkpa-final-reports.revision');
            Route::post('laporan-pkpa/{report}/reject', [FinalReportReviewController::class, 'reject'])->name('pkpa-final-reports.reject');
            Route::post('laporan-pkpa/{report}/bimbingan/{guidance}/approve', [FinalReportReviewController::class, 'approveGuidance'])->name('pkpa-final-reports.guidance.approve');
            Route::post('laporan-pkpa/{report}/bimbingan/{guidance}/revision', [FinalReportReviewController::class, 'revisionGuidance'])->name('pkpa-final-reports.guidance.revision');
            Route::get('laporan-pkpa/files/{file}/download', [FinalReportReviewController::class, 'download'])->name('pkpa-final-reports.files.download');
            Route::get('ujian-pkpa', [InternalExamScheduleController::class, 'index'])->name('pkpa-exams.index');
            Route::get('ujian-pkpa/{exam}', [InternalExamScheduleController::class, 'show'])->name('pkpa-exams.show');
            Route::get('mahasiswa-bimbingan', [SupervisedStudentController::class, 'index'])->name('assignments.index');
            Route::get('mahasiswa-bimbingan/{assignment}', [SupervisedStudentController::class, 'show'])->name('assignments.show');
            Route::get('logbook', [InternalLogbookMonitoringController::class, 'index'])->name('logbooks.index');
            Route::get('logbook/{logbook}', [InternalLogbookMonitoringController::class, 'show'])->name('logbooks.show');
            Route::post('logbook/{logbook}/comments', [InternalLogbookMonitoringController::class, 'comments'])->name('logbooks.comments');
            Route::get('logbook/{logbook}/evidence/download', [InternalLogbookMonitoringController::class, 'download'])->name('logbooks.evidence.download');
            Route::get('laporan-akhir', [FinalReportReviewController::class, 'index'])->name('final-reports.index');
            Route::get('laporan-akhir/{report}', [FinalReportReviewController::class, 'show'])->name('final-reports.show');
            Route::post('laporan-akhir/{report}/approve', [FinalReportReviewController::class, 'approve'])->name('final-reports.approve');
            Route::post('laporan-akhir/{report}/revision', [FinalReportReviewController::class, 'revision'])->name('final-reports.revision');
            Route::post('laporan-akhir/{report}/reject', [FinalReportReviewController::class, 'reject'])->name('final-reports.reject');
            Route::post('laporan-akhir/{report}/bimbingan/{guidance}/approve', [FinalReportReviewController::class, 'approveGuidance'])->name('final-reports.guidance.approve');
            Route::post('laporan-akhir/{report}/bimbingan/{guidance}/revision', [FinalReportReviewController::class, 'revisionGuidance'])->name('final-reports.guidance.revision');
            Route::get('laporan-akhir/files/{file}/download', [FinalReportReviewController::class, 'download'])->name('final-reports.files.download');
            Route::get('jadwal-sidang', [InternalExamScheduleController::class, 'index'])->name('exams.index');
            Route::get('jadwal-sidang/{exam}', [InternalExamScheduleController::class, 'show'])->name('exams.show');
            Route::get('penilaian', [InternalAssessmentController::class, 'index'])->name('assessments.index');
            Route::get('penilaian/{assignment}', [InternalAssessmentController::class, 'show'])->name('assessments.show');
            Route::post('penilaian/{assignment}/save', [InternalAssessmentController::class, 'save'])->name('assessments.save');
            Route::post('penilaian/{assignment}/submit', [InternalAssessmentController::class, 'submit'])->name('assessments.submit');
            Route::get('kompetensi', [InternalCompetencyController::class, 'index'])->name('competencies.index');
            Route::get('kompetensi/{assignment}', [InternalCompetencyController::class, 'show'])->name('competencies.show');
        });

        Route::middleware('role:pembimbing_lapangan')->prefix('pembimbing-lapangan')->name('field-supervisor.')->group(function () {
            Route::get('jadwal-pkpa', [FieldPkpaScheduleController::class, 'index'])->name('pkpa-schedule.index');
            Route::get('jadwal-pkpa/{assignment}', [FieldPkpaScheduleController::class, 'show'])->name('pkpa-schedule.show');
            Route::post('jadwal-pkpa/{assignment}/acknowledge', [FieldPkpaScheduleController::class, 'acknowledge'])->name('pkpa-schedule.acknowledge');
            Route::get('operasional-pkpa', [FieldPkpaRotationOperationController::class, 'index'])->name('pkpa-operations.index');
            Route::get('akademik-pkpa', [FieldPkpaAcademicRotationController::class, 'index'])->name('pkpa-academics.index');
            Route::get('penilaian-pkpa', [FieldPkpaAssessmentController::class, 'index'])->name('pkpa-assessments.index');
            Route::get('review-portofolio', [FieldPkpaPortfolioReviewController::class, 'index'])->name('pkpa-portfolios.index');
            Route::get('review-portofolio/{portfolio}', [FieldPkpaPortfolioReviewController::class, 'show'])->name('pkpa-portfolios.show');
            Route::post('review-portofolio/{portfolio}/verify', [FieldPkpaPortfolioReviewController::class, 'verify'])->name('pkpa-portfolios.verify');
            Route::post('review-portofolio/{portfolio}/revision', [FieldPkpaPortfolioReviewController::class, 'revision'])->name('pkpa-portfolios.revision');
            Route::post('penilaian-pkpa/scores/{score}/save', [FieldPkpaAssessmentController::class, 'save'])->name('pkpa-assessments.scores.save');
            Route::post('penilaian-pkpa/scores/{score}/submit', [FieldPkpaAssessmentController::class, 'submit'])->name('pkpa-assessments.scores.submit');
            Route::post('kompetensi-rotasi/{record}/review', [FieldPkpaAcademicRotationController::class, 'reviewCompetency'])->name('pkpa-competencies.review');
            Route::post('tugas-rotasi-submissions/{submission}/review', [FieldPkpaAcademicRotationController::class, 'reviewTask'])->name('pkpa-special-tasks.review');
            Route::post('laporan-rotasi/{report}/confirm', [FieldPkpaAcademicRotationController::class, 'confirmReport'])->name('pkpa-rotation-reports.confirm');
            Route::get('operasional-pkpa/{run}', [FieldPkpaRotationOperationController::class, 'show'])->name('pkpa-operations.show');
            Route::post('presensi-operasional/{record}/review', [FieldPkpaRotationOperationController::class, 'reviewAttendance'])->name('pkpa-attendance.review');
            Route::post('koreksi-presensi/{correction}/review', [FieldPkpaRotationOperationController::class, 'reviewCorrection'])->name('pkpa-attendance.corrections.review');
            Route::post('logbook-operasional/{entry}/review', [FieldPkpaRotationOperationController::class, 'reviewLogbook'])->name('pkpa-logbooks.review');
            Route::get('logbook-operasional/attachments/{attachment}/download', [FieldPkpaRotationOperationController::class, 'downloadAttachment'])->name('pkpa-logbooks.attachments.download');
            Route::get('mahasiswa-pkpa', [FieldStudentController::class, 'index'])->name('pkpa-students.index');
            Route::get('mahasiswa-pkpa/{assignment}', [FieldStudentController::class, 'show'])->name('pkpa-students.show');
            Route::get('jurnal-pkpa', [LogbookValidationController::class, 'index'])->name('pkpa-journals.index');
            Route::post('jurnal-pkpa/bulk-approve', [LogbookValidationController::class, 'bulkApprove'])->name('pkpa-journals.bulk-approve');
            Route::get('jurnal-pkpa/{logbook}', [LogbookValidationController::class, 'show'])->name('pkpa-journals.show');
            Route::post('jurnal-pkpa/{logbook}/approve', [LogbookValidationController::class, 'approve'])->name('pkpa-journals.approve');
            Route::post('jurnal-pkpa/{logbook}/revision', [LogbookValidationController::class, 'revision'])->name('pkpa-journals.revision');
            Route::post('jurnal-pkpa/{logbook}/reject', [LogbookValidationController::class, 'reject'])->name('pkpa-journals.reject');
            Route::get('jurnal-pkpa/{logbook}/evidence/download', [LogbookValidationController::class, 'download'])->name('pkpa-journals.evidence.download');
            Route::get('laporan-pkpa', [FieldFinalReportReviewController::class, 'index'])->name('pkpa-final-reports.index');
            Route::get('laporan-pkpa/{report}', [FieldFinalReportReviewController::class, 'show'])->name('pkpa-final-reports.show');
            Route::post('laporan-pkpa/{report}/approve', [FieldFinalReportReviewController::class, 'approve'])->name('pkpa-final-reports.approve');
            Route::post('laporan-pkpa/{report}/revision', [FieldFinalReportReviewController::class, 'revision'])->name('pkpa-final-reports.revision');
            Route::post('laporan-pkpa/{report}/reject', [FieldFinalReportReviewController::class, 'reject'])->name('pkpa-final-reports.reject');
            Route::get('laporan-pkpa/files/{file}/download', [FieldFinalReportReviewController::class, 'download'])->name('pkpa-final-reports.files.download');
            Route::get('mahasiswa-kp', [FieldStudentController::class, 'index'])->name('assignments.index');
            Route::get('mahasiswa-kp/{assignment}', [FieldStudentController::class, 'show'])->name('assignments.show');
            Route::get('logbook', [LogbookValidationController::class, 'index'])->name('logbooks.index');
            Route::post('logbook/bulk-approve', [LogbookValidationController::class, 'bulkApprove'])->name('logbooks.bulk-approve');
            Route::get('logbook/{logbook}', [LogbookValidationController::class, 'show'])->name('logbooks.show');
            Route::post('logbook/{logbook}/approve', [LogbookValidationController::class, 'approve'])->name('logbooks.approve');
            Route::post('logbook/{logbook}/revision', [LogbookValidationController::class, 'revision'])->name('logbooks.revision');
            Route::post('logbook/{logbook}/reject', [LogbookValidationController::class, 'reject'])->name('logbooks.reject');
            Route::get('logbook/{logbook}/evidence/download', [LogbookValidationController::class, 'download'])->name('logbooks.evidence.download');
            Route::get('laporan-akhir', [FieldFinalReportReviewController::class, 'index'])->name('final-reports.index');
            Route::get('laporan-akhir/{report}', [FieldFinalReportReviewController::class, 'show'])->name('final-reports.show');
            Route::post('laporan-akhir/{report}/approve', [FieldFinalReportReviewController::class, 'approve'])->name('final-reports.approve');
            Route::post('laporan-akhir/{report}/revision', [FieldFinalReportReviewController::class, 'revision'])->name('final-reports.revision');
            Route::post('laporan-akhir/{report}/reject', [FieldFinalReportReviewController::class, 'reject'])->name('final-reports.reject');
            Route::get('laporan-akhir/files/{file}/download', [FieldFinalReportReviewController::class, 'download'])->name('final-reports.files.download');
            Route::get('penilaian', [FieldAssessmentController::class, 'index'])->name('assessments.index');
            Route::get('penilaian/{assignment}', [FieldAssessmentController::class, 'show'])->name('assessments.show');
            Route::post('penilaian/{assignment}/save', [FieldAssessmentController::class, 'save'])->name('assessments.save');
            Route::post('penilaian/{assignment}/submit', [FieldAssessmentController::class, 'submit'])->name('assessments.submit');
            Route::get('kompetensi', [FieldCompetencyController::class, 'index'])->name('competencies.index');
            Route::get('kompetensi/{assignment}', [FieldCompetencyController::class, 'show'])->name('competencies.show');
            Route::put('kompetensi/{assignment}', [FieldCompetencyController::class, 'update'])->name('competencies.update');
        });

        Route::middleware('role:penguji')->prefix('penguji')->name('examiner.')->group(function () {
            Route::get('ujian-pkpa', [ExaminerExamScheduleController::class, 'index'])->name('pkpa-exams.index');
            Route::get('ujian-pkpa/{exam}', [ExaminerExamScheduleController::class, 'show'])->name('pkpa-exams.show');
            Route::get('jadwal-sidang', [ExaminerExamScheduleController::class, 'index'])->name('exams.index');
            Route::get('jadwal-sidang/{exam}', [ExaminerExamScheduleController::class, 'show'])->name('exams.show');
            Route::get('penilaian', [ExaminerAssessmentController::class, 'index'])->name('assessments.index');
            Route::get('penilaian/{exam}', [ExaminerAssessmentController::class, 'show'])->name('assessments.show');
            Route::post('penilaian/{exam}/save', [ExaminerAssessmentController::class, 'save'])->name('assessments.save');
            Route::post('penilaian/{exam}/submit', [ExaminerAssessmentController::class, 'submit'])->name('assessments.submit');
        });

        Route::get('/mahasiswa/dashboard', fn (DashboardController $controller, Request $request) => $controller->show($request, 'mahasiswa'))
            ->middleware('role:mahasiswa')
            ->name('mahasiswa.dashboard');
        Route::get('/admin/dashboard', fn (DashboardController $controller, Request $request) => $controller->show($request, 'admin'))
            ->middleware('role:admin')
            ->name('admin.dashboard');
        Route::get('/koordinator/dashboard', fn (DashboardController $controller, Request $request) => $controller->show($request, 'koordinator_kp'))
            ->middleware('role:koordinator_kp')
            ->name('koordinator.dashboard');
        Route::get('/pembimbing-dalam/dashboard', fn (DashboardController $controller, Request $request) => $controller->show($request, 'pembimbing_dalam'))
            ->middleware('role:pembimbing_dalam')
            ->name('pembimbing-dalam.dashboard');
        Route::get('/pembimbing-lapangan/dashboard', fn (DashboardController $controller, Request $request) => $controller->show($request, 'pembimbing_lapangan'))
            ->middleware('role:pembimbing_lapangan')
            ->name('pembimbing-lapangan.dashboard');
        Route::get('/penguji/dashboard', fn (DashboardController $controller, Request $request) => $controller->show($request, 'penguji'))
            ->middleware('role:penguji')
            ->name('penguji.dashboard');
    });
});
