@extends('layouts.app')
@section('title', 'Akademik Rotasi PKPA')
@section('page_title', 'Akademik Rotasi PKPA')
@section('content')
<div class="space-y-6">
    @if($errors->any())<div class="rounded-2xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm font-bold text-rose-700">{{ $errors->first() }}</div>@endif
    <section class="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
        @foreach(['Runtime' => $summary['runs'], 'Belum Ada Checklist' => $summary['without_competency'], 'Ready Assessment' => $summary['ready'], 'Blocked' => $summary['blocked']] as $label => $value)
            <div class="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-sky-100"><p class="text-xs font-black uppercase tracking-widest text-cyan-700">{{ $label }}</p><p class="mt-2 text-3xl font-black">{{ $value }}</p></div>
        @endforeach
    </section>
    <section class="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-sky-100">
        <div class="flex flex-wrap items-center justify-between gap-3"><div><p class="text-xs font-black uppercase tracking-widest text-cyan-700">Builder Akademik</p><h2 class="text-xl font-black">Kompetensi, Tugas, dan Template Laporan</h2></div><a href="{{ route('management.pkpa-academics.export') }}" class="rounded-xl border border-emerald-200 px-4 py-2 text-sm font-black text-emerald-700">Ekspor CSV</a></div>
        <div class="mt-4 grid gap-4 xl:grid-cols-2">
            @foreach($programDomains as $programDomain)
                <div class="rounded-xl border border-sky-100 p-4">
                    <p class="font-black text-slate-950">{{ $programDomain->program?->code }} / {{ $programDomain->practiceDomain?->name }}</p>
                    <p class="text-xs text-slate-500">Set aktif: {{ $programDomain->activeCompetencySet?->name ?? 'Belum ada' }} / Laporan: {{ $programDomain->activeReportTemplate?->name ?? 'Belum ada' }}</p>
                    <form method="POST" action="{{ route('management.pkpa-competency-sets.store', $programDomain) }}" class="mt-3 grid gap-2 sm:grid-cols-2">@csrf<input name="code" class="rounded-xl border-slate-200 text-sm" placeholder="Kode set" required><input name="name" class="rounded-xl border-slate-200 text-sm" placeholder="Nama set kompetensi" required><textarea name="instructions" class="rounded-xl border-slate-200 text-sm sm:col-span-2" placeholder="Instruksi"></textarea><button class="rounded-xl bg-cyan-700 px-3 py-2 text-xs font-black text-white sm:col-span-2">Buat Set Kompetensi</button></form>
                    @if($programDomain->competencySets->isNotEmpty())
                        @foreach($programDomain->competencySets as $set)
                            <form method="POST" action="{{ route('management.pkpa-competency-items.store', $set) }}" class="mt-3 grid gap-2 rounded-xl bg-slate-50 p-3 sm:grid-cols-2">@csrf<p class="sm:col-span-2 text-sm font-black">{{ $set->name }} v{{ $set->version_number }} / {{ $set->status }}</p><input name="code" class="rounded-xl border-slate-200 text-sm" placeholder="Kode item" required><input name="title" class="rounded-xl border-slate-200 text-sm" placeholder="Judul kompetensi" required><label class="text-xs font-bold"><input type="checkbox" name="is_required" value="1" checked> Wajib</label><label class="text-xs font-bold"><input type="checkbox" name="evidence_required" value="1"> Bukti wajib</label><input name="minimum_evidence_count" type="number" min="0" class="rounded-xl border-slate-200 text-sm" placeholder="Minimal bukti"><button class="rounded-xl border border-cyan-200 px-3 py-2 text-xs font-black text-cyan-700">Simpan Item</button></form>
                            @if($set->status !== 'active')<form method="POST" action="{{ route('management.pkpa-competency-sets.activate', $set) }}" class="mt-2">@csrf<button class="rounded-xl bg-slate-900 px-3 py-2 text-xs font-black text-white">Aktifkan Set Ini</button></form>@endif
                        @endforeach
                    @endif
                    <form method="POST" action="{{ route('management.pkpa-special-task-templates.store', $programDomain) }}" class="mt-3 grid gap-2 sm:grid-cols-2">@csrf<input name="code" class="rounded-xl border-slate-200 text-sm" placeholder="Kode tugas" required><input name="title" class="rounded-xl border-slate-200 text-sm" placeholder="Judul tugas" required><select name="submission_type" class="rounded-xl border-slate-200 text-sm"><option value="document">Dokumen</option><option value="presentation">Presentasi</option><option value="case_report">Laporan Kasus</option><option value="project">Proyek</option><option value="reflection">Refleksi</option><option value="mixed">Campuran</option></select><input name="due_offset_days" type="number" class="rounded-xl border-slate-200 text-sm" placeholder="Offset due date"><label class="text-xs font-bold"><input type="checkbox" name="field_supervisor_review_required" value="1"> Review PL</label><button class="rounded-xl border border-cyan-200 px-3 py-2 text-xs font-black text-cyan-700">Simpan Tugas</button></form>
                    <form method="POST" action="{{ route('management.pkpa-rotation-report-templates.store', $programDomain) }}" class="mt-3 grid gap-2 sm:grid-cols-2">@csrf<input name="code" class="rounded-xl border-slate-200 text-sm" placeholder="Kode laporan" required><input name="name" class="rounded-xl border-slate-200 text-sm" placeholder="Nama laporan" required><input name="maximum_file_size_kb" type="number" class="rounded-xl border-slate-200 text-sm" placeholder="Maks KB"><label class="text-xs font-bold"><input type="checkbox" name="field_supervisor_confirmation_required" value="1"> Konfirmasi PL</label><button class="rounded-xl border border-cyan-200 px-3 py-2 text-xs font-black text-cyan-700 sm:col-span-2">Simpan Template Laporan</button></form>
                </div>
            @endforeach
        </div>
    </section>
    <section class="overflow-hidden rounded-2xl bg-white shadow-sm ring-1 ring-sky-100">
        <div class="border-b border-sky-100 px-5 py-4"><h2 class="text-xl font-black">Monitoring Runtime Akademik</h2></div>
        <div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-100 text-sm"><thead class="bg-slate-50 text-left text-xs font-black uppercase tracking-widest text-slate-500"><tr><th class="px-4 py-3">Mahasiswa</th><th class="px-4 py-3">Wahana</th><th class="px-4 py-3">Kompetensi</th><th class="px-4 py-3">Tugas</th><th class="px-4 py-3">Laporan</th><th class="px-4 py-3">Aksi</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($runs as $run)<tr><td class="px-4 py-3 font-black">{{ $run->student_core_user_id }}</td><td class="px-4 py-3">{{ $run->practiceDomain?->name }}<br><span class="text-xs text-slate-500">{{ $run->practiceSite?->name }}</span></td><td class="px-4 py-3">{{ $run->competencyRecords->where('status','verified')->count() }}/{{ $run->competencyRecords->where('is_required_snapshot', true)->count() }}</td><td class="px-4 py-3">{{ $run->specialTasks->where('status','approved')->count() }}/{{ $run->specialTasks->where('is_required_snapshot', true)->count() }}</td><td class="px-4 py-3">{{ $run->rotationReport?->status ?? '-' }}</td><td class="px-4 py-3"><div class="flex flex-wrap gap-2"><form method="POST" action="{{ route('management.pkpa-rotation-runs.competency-checklist', $run) }}">@csrf<button class="rounded-lg border border-cyan-200 px-3 py-1.5 text-xs font-black text-cyan-700">Checklist</button></form><form method="POST" action="{{ route('management.pkpa-rotation-runs.special-tasks', $run) }}">@csrf<button class="rounded-lg border border-cyan-200 px-3 py-1.5 text-xs font-black text-cyan-700">Tugas</button></form><form method="POST" action="{{ route('management.pkpa-rotation-runs.academic-readiness', $run) }}">@csrf<button class="rounded-lg bg-slate-900 px-3 py-1.5 text-xs font-black text-white">Readiness</button></form></div></td></tr>@empty<tr><td colspan="6" class="px-4 py-8 text-center text-slate-500">Belum ada runtime akademik.</td></tr>@endforelse</tbody></table></div><div class="px-5 py-4">{{ $runs->links() }}</div>
    </section>
</div>
@endsection
