@extends('layouts.app')
@section('title', 'Monitoring Logbook PKPA')
@section('page_title', 'Monitoring Logbook PKPA')
@section('content')
@php
    $statusLabel = ['submitted' => 'Menunggu Preseptor', 'field_approved' => 'Disetujui Preseptor', 'internal_approved' => 'Tervalidasi Final', 'revision_requested' => 'Perlu Revisi', 'rejected' => 'Ditolak'];
    $canValidate = $selectedLogbook && in_array($selectedLogbook->status, ['field_approved', 'approved'], true);
@endphp
<div class="space-y-5">
    @if(session('status'))<div class="rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-700">{{ session('status') }}</div>@endif
    @if($errors->any())<div class="rounded-2xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm font-bold text-rose-700">{{ $errors->first() }}</div>@endif
    @if($selectedLogbook)
        <a href="{{ route('internal-supervisor.pkpa-operations.show', $run) }}" class="inline-flex min-h-10 items-center rounded-xl border border-slate-200 bg-white px-4 text-sm font-bold text-slate-700">Kembali ke Daftar</a>
        <section class="rounded-2xl bg-white p-6 shadow-sm ring-1 {{ $canValidate ? 'ring-emerald-200' : 'ring-slate-200' }}"><div class="flex flex-wrap items-start justify-between gap-3"><div><p class="text-xs font-black uppercase tracking-widest text-cyan-700">{{ $run->studentDisplayName() }} · {{ $selectedLogbook->entry_date?->format('d M Y') }}</p><h2 class="mt-2 text-2xl font-black text-slate-950">{{ $selectedLogbook->title }}</h2></div><span class="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold text-slate-700">{{ $statusLabel[$selectedLogbook->status] ?? str($selectedLogbook->status)->headline() }}</span></div><div class="mt-5 grid gap-3 lg:grid-cols-2"><div class="rounded-xl bg-slate-50 p-4"><p class="text-xs font-black uppercase text-slate-500">Uraian Aktivitas</p><p class="mt-2 text-sm leading-6">{{ $selectedLogbook->activity_summary }}</p></div><div class="rounded-xl bg-slate-50 p-4"><p class="text-xs font-black uppercase text-slate-500">Kompetensi</p><p class="mt-2 text-sm leading-6">{{ $selectedLogbook->learning_outcomes }}</p></div><div class="rounded-xl bg-slate-50 p-4 lg:col-span-2"><p class="text-xs font-black uppercase text-slate-500">Refleksi</p><p class="mt-2 text-sm leading-6">{{ $selectedLogbook->reflection }}</p></div></div><div class="mt-4 space-y-2">@forelse($selectedLogbook->attachments as $attachment)<div class="flex items-center justify-between gap-3 rounded-xl border border-slate-200 p-3"><span class="text-sm font-bold">{{ $attachment->displayLabel() }}</span><a href="{{ $attachment->isExternalLink() ? $attachment->previewUrl() : route('internal-supervisor.pkpa-logbooks.attachments.download', $attachment) }}" target="_blank" class="text-sm font-bold text-cyan-700">{{ $attachment->isExternalLink() ? 'Preview Bukti' : 'Unduh Bukti' }}</a></div>@empty<p class="text-sm text-slate-500">Belum ada bukti terlampir.</p>@endforelse</div>@if($canValidate)<form method="POST" action="{{ route('internal-supervisor.pkpa-logbooks.monitoring', $selectedLogbook) }}" class="mt-5 border-t pt-5">@csrf<textarea name="comments" class="min-h-28 w-full rounded-xl border-slate-200" placeholder="Catatan validasi; wajib untuk revisi atau penolakan"></textarea><div class="mt-3 flex gap-2"><button name="action" value="approved" class="rounded-xl bg-emerald-600 px-4 py-2 text-sm font-bold text-white">Validasi Final</button><button name="action" value="revision_requested" class="rounded-xl border border-amber-200 px-4 py-2 text-sm font-bold text-amber-700">Minta Revisi</button><button name="action" value="rejected" class="rounded-xl border border-rose-200 px-4 py-2 text-sm font-bold text-rose-700">Tolak</button></div></form>@else<div class="mt-5 rounded-xl bg-amber-50 p-4 text-sm text-amber-900">{{ $selectedLogbook->status === 'submitted' ? 'Logbook masih menunggu keputusan Preseptor. Pembimbing Dalam belum dapat memvalidasi.' : 'Logbook ini tidak memerlukan validasi akhir pada status saat ini.' }}</div>@endif</section>
    @else
        <section class="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-sky-100"><p class="text-xs font-black uppercase tracking-widest text-cyan-700">{{ $run->practiceDomain?->name }}</p><h2 class="mt-1 text-2xl font-black">{{ $run->studentDisplayName() }}</h2><p class="mt-1 text-sm text-slate-500">{{ $run->practiceSite?->name }}</p><div class="mt-4 grid gap-3 sm:grid-cols-3"><div class="rounded-xl bg-slate-50 p-3"><p class="text-xs font-black uppercase text-slate-500">Presensi Terkirim</p><p class="mt-1 font-black">{{ $attendanceCount }}</p></div><div class="rounded-xl bg-amber-50 p-3"><p class="text-xs font-black uppercase text-amber-700">Menunggu Preseptor</p><p class="mt-1 font-black">{{ $waitingFieldCount }}</p></div><div class="rounded-xl bg-emerald-50 p-3"><p class="text-xs font-black uppercase text-emerald-700">Siap Validasi Akhir</p><p class="mt-1 font-black">{{ $readyCount }}</p></div></div></section>
        <section class="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-sky-100"><h3 class="text-lg font-black">Daftar Presensi</h3><div class="mt-3 divide-y divide-slate-100">@forelse($attendances as $record)<div class="flex items-center justify-between gap-3 py-3"><div><p class="font-bold">{{ $record->attendance_date?->format('d M Y') }} · {{ $record->check_in_time ?: '-' }} - {{ $record->check_out_time ?: '-' }}</p><p class="text-sm text-slate-500">{{ $record->submission_status === 'approved' ? 'Disetujui Preseptor' : ($record->submission_status === 'submitted' ? 'Menunggu Preseptor' : 'Perlu tindak lanjut') }}</p></div></div>@empty<p class="py-6 text-sm text-slate-500">Belum ada presensi terkirim.</p>@endforelse</div>{{ $attendances->links() }}</section>
        <section class="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-sky-100"><h3 class="text-lg font-black">Daftar Logbook</h3><p class="mt-1 text-sm text-slate-500">Klik detail untuk membaca isi lengkap. Hanya status Disetujui Preseptor yang dapat divalidasi.</p><div class="mt-3 divide-y divide-slate-100">@forelse($logbooks as $entry)<a href="{{ route('internal-supervisor.pkpa-operations.show', ['run' => $run, 'logbook' => $entry->id]) }}" class="flex items-center justify-between gap-3 py-3"><div><p class="font-bold text-slate-950">{{ $entry->entry_date?->format('d M Y') }} · {{ $entry->title }}</p><p class="text-sm text-slate-500">{{ $statusLabel[$entry->status] ?? str($entry->status)->headline() }}</p></div><span class="rounded-xl border border-cyan-200 px-3 py-2 text-sm font-bold text-cyan-700">Lihat Detail</span></a>@empty<p class="py-6 text-sm text-slate-500">Belum ada logbook terkirim.</p>@endforelse</div>{{ $logbooks->links() }}</section>
    @endif
</div>
@endsection
