<?php

return [
    'local_account_management_enabled' => (bool) env('MY_PSPA_LOCAL_ACCOUNT_MANAGEMENT_ENABLED', false),
    'student_place_selection_enabled' => (bool) env('MY_PSPA_STUDENT_PLACE_SELECTION_ENABLED', false),
    'publication_enabled' => (bool) env('PKPA_PUBLICATION_ENABLED', true),
    'rotation_operations_enabled' => (bool) env('PKPA_ROTATION_OPERATIONS_ENABLED', true),
    'database_notifications_enabled' => (bool) env('PKPA_DATABASE_NOTIFICATIONS_ENABLED', true),
    'email_notifications_enabled' => (bool) env('PKPA_EMAIL_NOTIFICATIONS_ENABLED', false),
    'notification_from_name' => env('PKPA_NOTIFICATION_FROM_NAME', env('MAIL_FROM_NAME', 'MY PSPA')),
    'notification_reply_to' => env('PKPA_NOTIFICATION_REPLY_TO'),
    'logbook_attachment_disk' => env('PKPA_LOGBOOK_ATTACHMENT_DISK', 'local'),
    'logbook_attachment_max_kb' => (int) env('PKPA_LOGBOOK_ATTACHMENT_MAX_KB', 5120),
    'logbook_attachment_allowed_mimes' => ['application/pdf', 'image/jpeg', 'image/png', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'],
    'competency_enabled' => (bool) env('PKPA_COMPETENCY_ENABLED', true),
    'special_task_enabled' => (bool) env('PKPA_SPECIAL_TASK_ENABLED', true),
    'rotation_report_enabled' => (bool) env('PKPA_ROTATION_REPORT_ENABLED', true),
    'guidance_enabled' => (bool) env('PKPA_GUIDANCE_ENABLED', true),
    'academic_database_notifications_enabled' => (bool) env('PKPA_ACADEMIC_DATABASE_NOTIFICATIONS_ENABLED', true),
    'academic_email_notifications_enabled' => (bool) env('PKPA_ACADEMIC_EMAIL_NOTIFICATIONS_ENABLED', false),
    'academic_file_disk' => env('PKPA_ACADEMIC_FILE_DISK', 'local'),
    'academic_file_max_size_kb' => (int) env('PKPA_ACADEMIC_FILE_MAX_SIZE_KB', 5120),
    'academic_allowed_mime_types' => array_filter(array_map('trim', explode(',', env('PKPA_ACADEMIC_ALLOWED_MIME_TYPES', 'application/pdf,image/jpeg,image/png,application/vnd.openxmlformats-officedocument.wordprocessingml.document')))),
    'assessment_enabled' => (bool) env('PKPA_ASSESSMENT_ENABLED', true),
    'assessment_moderation_enabled' => (bool) env('PKPA_ASSESSMENT_MODERATION_ENABLED', true),
    'grade_release_enabled' => (bool) env('PKPA_GRADE_RELEASE_ENABLED', true),
    'assessment_database_notifications_enabled' => (bool) env('PKPA_ASSESSMENT_DATABASE_NOTIFICATIONS_ENABLED', true),
    'assessment_email_notifications_enabled' => (bool) env('PKPA_ASSESSMENT_EMAIL_NOTIFICATIONS_ENABLED', false),
    'hide_other_assessor_scores_until_submit' => (bool) env('PKPA_HIDE_OTHER_ASSESSOR_SCORES_UNTIL_SUBMIT', true),
    'final_grade_enabled' => (bool) env('PKPA_FINAL_GRADE_ENABLED', true),
    'remedial_enabled' => (bool) env('PKPA_REMEDIAL_ENABLED', true),
    'program_assessment_enabled' => (bool) env('PKPA_PROGRAM_ASSESSMENT_ENABLED', true),
    'graduation_decision_enabled' => (bool) env('PKPA_GRADUATION_DECISION_ENABLED', true),
    'final_result_release_enabled' => (bool) env('PKPA_FINAL_RESULT_RELEASE_ENABLED', true),
    'final_database_notifications_enabled' => (bool) env('PKPA_FINAL_DATABASE_NOTIFICATIONS_ENABLED', true),
    'final_email_notifications_enabled' => (bool) env('PKPA_FINAL_EMAIL_NOTIFICATIONS_ENABLED', false),
    'document_automation_enabled' => (bool) env('PKPA_DOCUMENT_AUTOMATION_ENABLED', true),
    'document_email_enabled' => (bool) env('PKPA_DOCUMENT_EMAIL_ENABLED', false),
    'document_disk' => env('PKPA_DOCUMENT_DISK', 'local'),
    'document_max_size_kb' => (int) env('PKPA_DOCUMENT_MAX_SIZE_KB', 10240),
    'analytics_enabled' => (bool) env('PKPA_ANALYTICS_ENABLED', true),
    'account_urls' => [
        'register' => env('CORE_FARMASI_REGISTER_URL'),
        'forgot_password' => env('CORE_FARMASI_FORGOT_PASSWORD_URL'),
        'manage' => env('CORE_FARMASI_ACCOUNT_URL'),
    ],
];
